// Code generated by go-swagger; DO NOT EDIT.

package cloud

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetCloudJobParams creates a new GetCloudJobParams object
// with the default values initialized.
func NewGetCloudJobParams() *GetCloudJobParams {
	var ()
	return &GetCloudJobParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetCloudJobParamsWithTimeout creates a new GetCloudJobParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetCloudJobParamsWithTimeout(timeout time.Duration) *GetCloudJobParams {
	var ()
	return &GetCloudJobParams{

		timeout: timeout,
	}
}

// NewGetCloudJobParamsWithContext creates a new GetCloudJobParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetCloudJobParamsWithContext(ctx context.Context) *GetCloudJobParams {
	var ()
	return &GetCloudJobParams{

		Context: ctx,
	}
}

// NewGetCloudJobParamsWithHTTPClient creates a new GetCloudJobParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetCloudJobParamsWithHTTPClient(client *http.Client) *GetCloudJobParams {
	var ()
	return &GetCloudJobParams{
		HTTPClient: client,
	}
}

/*GetCloudJobParams contains all the parameters to send to the API endpoint
for the get cloud job operation typically these are written to a http.Request
*/
type GetCloudJobParams struct {

	/*CloudJobID
	  Retrieve cloudpool job information.

	*/
	CloudJobID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get cloud job params
func (o *GetCloudJobParams) WithTimeout(timeout time.Duration) *GetCloudJobParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get cloud job params
func (o *GetCloudJobParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get cloud job params
func (o *GetCloudJobParams) WithContext(ctx context.Context) *GetCloudJobParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get cloud job params
func (o *GetCloudJobParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get cloud job params
func (o *GetCloudJobParams) WithHTTPClient(client *http.Client) *GetCloudJobParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get cloud job params
func (o *GetCloudJobParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCloudJobID adds the cloudJobID to the get cloud job params
func (o *GetCloudJobParams) WithCloudJobID(cloudJobID string) *GetCloudJobParams {
	o.SetCloudJobID(cloudJobID)
	return o
}

// SetCloudJobID adds the cloudJobId to the get cloud job params
func (o *GetCloudJobParams) SetCloudJobID(cloudJobID string) {
	o.CloudJobID = cloudJobID
}

// WriteToRequest writes these params to a swagger request
func (o *GetCloudJobParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param CloudJobId
	if err := r.SetPathParam("CloudJobId", o.CloudJobID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
