// Code generated by go-swagger; DO NOT EDIT.

package cloud

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListCloudPoolsParams creates a new ListCloudPoolsParams object
// with the default values initialized.
func NewListCloudPoolsParams() *ListCloudPoolsParams {
	var ()
	return &ListCloudPoolsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListCloudPoolsParamsWithTimeout creates a new ListCloudPoolsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListCloudPoolsParamsWithTimeout(timeout time.Duration) *ListCloudPoolsParams {
	var ()
	return &ListCloudPoolsParams{

		timeout: timeout,
	}
}

// NewListCloudPoolsParamsWithContext creates a new ListCloudPoolsParams object
// with the default values initialized, and the ability to set a context for a request
func NewListCloudPoolsParamsWithContext(ctx context.Context) *ListCloudPoolsParams {
	var ()
	return &ListCloudPoolsParams{

		Context: ctx,
	}
}

// NewListCloudPoolsParamsWithHTTPClient creates a new ListCloudPoolsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListCloudPoolsParamsWithHTTPClient(client *http.Client) *ListCloudPoolsParams {
	var ()
	return &ListCloudPoolsParams{
		HTTPClient: client,
	}
}

/*ListCloudPoolsParams contains all the parameters to send to the API endpoint
for the list cloud pools operation typically these are written to a http.Request
*/
type ListCloudPoolsParams struct {

	/*Dir
	  The direction of the sort.

	*/
	Dir *string
	/*Limit
	  Return no more than this many results at once (see resume).

	*/
	Limit *int64
	/*Sort
	  The field that will be used for sorting.

	*/
	Sort *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list cloud pools params
func (o *ListCloudPoolsParams) WithTimeout(timeout time.Duration) *ListCloudPoolsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list cloud pools params
func (o *ListCloudPoolsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list cloud pools params
func (o *ListCloudPoolsParams) WithContext(ctx context.Context) *ListCloudPoolsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list cloud pools params
func (o *ListCloudPoolsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list cloud pools params
func (o *ListCloudPoolsParams) WithHTTPClient(client *http.Client) *ListCloudPoolsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list cloud pools params
func (o *ListCloudPoolsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDir adds the dir to the list cloud pools params
func (o *ListCloudPoolsParams) WithDir(dir *string) *ListCloudPoolsParams {
	o.SetDir(dir)
	return o
}

// SetDir adds the dir to the list cloud pools params
func (o *ListCloudPoolsParams) SetDir(dir *string) {
	o.Dir = dir
}

// WithLimit adds the limit to the list cloud pools params
func (o *ListCloudPoolsParams) WithLimit(limit *int64) *ListCloudPoolsParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the list cloud pools params
func (o *ListCloudPoolsParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithSort adds the sort to the list cloud pools params
func (o *ListCloudPoolsParams) WithSort(sort *string) *ListCloudPoolsParams {
	o.SetSort(sort)
	return o
}

// SetSort adds the sort to the list cloud pools params
func (o *ListCloudPoolsParams) SetSort(sort *string) {
	o.Sort = sort
}

// WriteToRequest writes these params to a swagger request
func (o *ListCloudPoolsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Dir != nil {

		// query param dir
		var qrDir string
		if o.Dir != nil {
			qrDir = *o.Dir
		}
		qDir := qrDir
		if qDir != "" {
			if err := r.SetQueryParam("dir", qDir); err != nil {
				return err
			}
		}

	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {
			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	if o.Sort != nil {

		// query param sort
		var qrSort string
		if o.Sort != nil {
			qrSort = *o.Sort
		}
		qSort := qrSort
		if qSort != "" {
			if err := r.SetQueryParam("sort", qSort); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
