// Code generated by go-swagger; DO NOT EDIT.

package quota

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/tenortim/isi_sdk_go/models"
)

// CreateQuotaReportReader is a Reader for the CreateQuotaReport structure.
type CreateQuotaReportReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateQuotaReportReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCreateQuotaReportOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewCreateQuotaReportDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCreateQuotaReportOK creates a CreateQuotaReportOK with default headers values
func NewCreateQuotaReportOK() *CreateQuotaReportOK {
	return &CreateQuotaReportOK{}
}

/*CreateQuotaReportOK handles this case with default header values.

Create a new report. The type of this report is 'manual'; it is also sometimes called 'live' or 'ad-hoc'.
*/
type CreateQuotaReportOK struct {
	Payload *models.CreateQuotaReportResponse
}

func (o *CreateQuotaReportOK) Error() string {
	return fmt.Sprintf("[POST /platform/1/quota/reports][%d] createQuotaReportOK  %+v", 200, o.Payload)
}

func (o *CreateQuotaReportOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CreateQuotaReportResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateQuotaReportDefault creates a CreateQuotaReportDefault with default headers values
func NewCreateQuotaReportDefault(code int) *CreateQuotaReportDefault {
	return &CreateQuotaReportDefault{
		_statusCode: code,
	}
}

/*CreateQuotaReportDefault handles this case with default header values.

Unexpected error
*/
type CreateQuotaReportDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the create quota report default response
func (o *CreateQuotaReportDefault) Code() int {
	return o._statusCode
}

func (o *CreateQuotaReportDefault) Error() string {
	return fmt.Sprintf("[POST /platform/1/quota/reports][%d] createQuotaReport default  %+v", o._statusCode, o.Payload)
}

func (o *CreateQuotaReportDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
