// Code generated by go-swagger; DO NOT EDIT.

package quota

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/tenortim/isi_sdk_go/models"
)

// CreateSettingsMappingReader is a Reader for the CreateSettingsMapping structure.
type CreateSettingsMappingReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateSettingsMappingReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCreateSettingsMappingOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewCreateSettingsMappingDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCreateSettingsMappingOK creates a CreateSettingsMappingOK with default headers values
func NewCreateSettingsMappingOK() *CreateSettingsMappingOK {
	return &CreateSettingsMappingOK{}
}

/*CreateSettingsMappingOK handles this case with default header values.

Create a new rule. The new rule must not conflict with an existing rule (e.g. match both the type and domain fields).
*/
type CreateSettingsMappingOK struct {
	Payload *models.CreateResponse
}

func (o *CreateSettingsMappingOK) Error() string {
	return fmt.Sprintf("[POST /platform/1/quota/settings/mappings][%d] createSettingsMappingOK  %+v", 200, o.Payload)
}

func (o *CreateSettingsMappingOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CreateResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateSettingsMappingDefault creates a CreateSettingsMappingDefault with default headers values
func NewCreateSettingsMappingDefault(code int) *CreateSettingsMappingDefault {
	return &CreateSettingsMappingDefault{
		_statusCode: code,
	}
}

/*CreateSettingsMappingDefault handles this case with default header values.

Unexpected error
*/
type CreateSettingsMappingDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the create settings mapping default response
func (o *CreateSettingsMappingDefault) Code() int {
	return o._statusCode
}

func (o *CreateSettingsMappingDefault) Error() string {
	return fmt.Sprintf("[POST /platform/1/quota/settings/mappings][%d] createSettingsMapping default  %+v", o._statusCode, o.Payload)
}

func (o *CreateSettingsMappingDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
