// Code generated by go-swagger; DO NOT EDIT.

package quota

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/tenortim/isi_sdk_go/models"
)

// GetQuotaLicenseReader is a Reader for the GetQuotaLicense structure.
type GetQuotaLicenseReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetQuotaLicenseReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetQuotaLicenseOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetQuotaLicenseDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetQuotaLicenseOK creates a GetQuotaLicenseOK with default headers values
func NewGetQuotaLicenseOK() *GetQuotaLicenseOK {
	return &GetQuotaLicenseOK{}
}

/*GetQuotaLicenseOK handles this case with default header values.

Retrieve license information.
*/
type GetQuotaLicenseOK struct {
	Payload *models.LicenseLicense
}

func (o *GetQuotaLicenseOK) Error() string {
	return fmt.Sprintf("[GET /platform/1/quota/license][%d] getQuotaLicenseOK  %+v", 200, o.Payload)
}

func (o *GetQuotaLicenseOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.LicenseLicense)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetQuotaLicenseDefault creates a GetQuotaLicenseDefault with default headers values
func NewGetQuotaLicenseDefault(code int) *GetQuotaLicenseDefault {
	return &GetQuotaLicenseDefault{
		_statusCode: code,
	}
}

/*GetQuotaLicenseDefault handles this case with default header values.

Unexpected error
*/
type GetQuotaLicenseDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get quota license default response
func (o *GetQuotaLicenseDefault) Code() int {
	return o._statusCode
}

func (o *GetQuotaLicenseDefault) Error() string {
	return fmt.Sprintf("[GET /platform/1/quota/license][%d] getQuotaLicense default  %+v", o._statusCode, o.Payload)
}

func (o *GetQuotaLicenseDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
