// Code generated by go-swagger; DO NOT EDIT.

package snapshot_snapshots

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/tenortim/isi_sdk_go/models"
)

// UpdateSnapshotLockReader is a Reader for the UpdateSnapshotLock structure.
type UpdateSnapshotLockReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateSnapshotLockReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewUpdateSnapshotLockNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewUpdateSnapshotLockDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewUpdateSnapshotLockNoContent creates a UpdateSnapshotLockNoContent with default headers values
func NewUpdateSnapshotLockNoContent() *UpdateSnapshotLockNoContent {
	return &UpdateSnapshotLockNoContent{}
}

/*UpdateSnapshotLockNoContent handles this case with default header values.

Success.
*/
type UpdateSnapshotLockNoContent struct {
}

func (o *UpdateSnapshotLockNoContent) Error() string {
	return fmt.Sprintf("[PUT /platform/1/snapshot/snapshots/{Sid}/locks/{SnapshotLockId}][%d] updateSnapshotLockNoContent ", 204)
}

func (o *UpdateSnapshotLockNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateSnapshotLockDefault creates a UpdateSnapshotLockDefault with default headers values
func NewUpdateSnapshotLockDefault(code int) *UpdateSnapshotLockDefault {
	return &UpdateSnapshotLockDefault{
		_statusCode: code,
	}
}

/*UpdateSnapshotLockDefault handles this case with default header values.

Unexpected error
*/
type UpdateSnapshotLockDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the update snapshot lock default response
func (o *UpdateSnapshotLockDefault) Code() int {
	return o._statusCode
}

func (o *UpdateSnapshotLockDefault) Error() string {
	return fmt.Sprintf("[PUT /platform/1/snapshot/snapshots/{Sid}/locks/{SnapshotLockId}][%d] updateSnapshotLock default  %+v", o._statusCode, o.Payload)
}

func (o *UpdateSnapshotLockDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
