// Code generated by go-swagger; DO NOT EDIT.

package event

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/tenortim/isi_sdk_go/models"
)

// UpdateEventAlertConditionReader is a Reader for the UpdateEventAlertCondition structure.
type UpdateEventAlertConditionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateEventAlertConditionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewUpdateEventAlertConditionNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewUpdateEventAlertConditionDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewUpdateEventAlertConditionNoContent creates a UpdateEventAlertConditionNoContent with default headers values
func NewUpdateEventAlertConditionNoContent() *UpdateEventAlertConditionNoContent {
	return &UpdateEventAlertConditionNoContent{}
}

/*UpdateEventAlertConditionNoContent handles this case with default header values.

Success.
*/
type UpdateEventAlertConditionNoContent struct {
}

func (o *UpdateEventAlertConditionNoContent) Error() string {
	return fmt.Sprintf("[PUT /platform/3/event/alert-conditions/{EventAlertConditionId}][%d] updateEventAlertConditionNoContent ", 204)
}

func (o *UpdateEventAlertConditionNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateEventAlertConditionDefault creates a UpdateEventAlertConditionDefault with default headers values
func NewUpdateEventAlertConditionDefault(code int) *UpdateEventAlertConditionDefault {
	return &UpdateEventAlertConditionDefault{
		_statusCode: code,
	}
}

/*UpdateEventAlertConditionDefault handles this case with default header values.

Unexpected error
*/
type UpdateEventAlertConditionDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the update event alert condition default response
func (o *UpdateEventAlertConditionDefault) Code() int {
	return o._statusCode
}

func (o *UpdateEventAlertConditionDefault) Error() string {
	return fmt.Sprintf("[PUT /platform/3/event/alert-conditions/{EventAlertConditionId}][%d] updateEventAlertCondition default  %+v", o._statusCode, o.Payload)
}

func (o *UpdateEventAlertConditionDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
