// Code generated by go-swagger; DO NOT EDIT.

package antivirus

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/tenortim/isi_sdk_go/models"
)

// GetReportsScansReader is a Reader for the GetReportsScans structure.
type GetReportsScansReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetReportsScansReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetReportsScansOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetReportsScansDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetReportsScansOK creates a GetReportsScansOK with default headers values
func NewGetReportsScansOK() *GetReportsScansOK {
	return &GetReportsScansOK{}
}

/*GetReportsScansOK handles this case with default header values.

List antivirus scan reports.
*/
type GetReportsScansOK struct {
	Payload *models.ReportsScansExtended
}

func (o *GetReportsScansOK) Error() string {
	return fmt.Sprintf("[GET /platform/3/antivirus/reports/scans][%d] getReportsScansOK  %+v", 200, o.Payload)
}

func (o *GetReportsScansOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ReportsScansExtended)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetReportsScansDefault creates a GetReportsScansDefault with default headers values
func NewGetReportsScansDefault(code int) *GetReportsScansDefault {
	return &GetReportsScansDefault{
		_statusCode: code,
	}
}

/*GetReportsScansDefault handles this case with default header values.

Unexpected error
*/
type GetReportsScansDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get reports scans default response
func (o *GetReportsScansDefault) Code() int {
	return o._statusCode
}

func (o *GetReportsScansDefault) Error() string {
	return fmt.Sprintf("[GET /platform/3/antivirus/reports/scans][%d] getReportsScans default  %+v", o._statusCode, o.Payload)
}

func (o *GetReportsScansDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
