// Code generated by go-swagger; DO NOT EDIT.

package antivirus

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/tenortim/isi_sdk_go/models"
)

// ListAntivirusServersReader is a Reader for the ListAntivirusServers structure.
type ListAntivirusServersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListAntivirusServersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewListAntivirusServersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewListAntivirusServersDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewListAntivirusServersOK creates a ListAntivirusServersOK with default headers values
func NewListAntivirusServersOK() *ListAntivirusServersOK {
	return &ListAntivirusServersOK{}
}

/*ListAntivirusServersOK handles this case with default header values.

List antivirus servers.
*/
type ListAntivirusServersOK struct {
	Payload *models.AntivirusServersExtended
}

func (o *ListAntivirusServersOK) Error() string {
	return fmt.Sprintf("[GET /platform/3/antivirus/servers][%d] listAntivirusServersOK  %+v", 200, o.Payload)
}

func (o *ListAntivirusServersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AntivirusServersExtended)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListAntivirusServersDefault creates a ListAntivirusServersDefault with default headers values
func NewListAntivirusServersDefault(code int) *ListAntivirusServersDefault {
	return &ListAntivirusServersDefault{
		_statusCode: code,
	}
}

/*ListAntivirusServersDefault handles this case with default header values.

Unexpected error
*/
type ListAntivirusServersDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the list antivirus servers default response
func (o *ListAntivirusServersDefault) Code() int {
	return o._statusCode
}

func (o *ListAntivirusServersDefault) Error() string {
	return fmt.Sprintf("[GET /platform/3/antivirus/servers][%d] listAntivirusServers default  %+v", o._statusCode, o.Payload)
}

func (o *ListAntivirusServersDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
