// Code generated by go-swagger; DO NOT EDIT.

package network_groupnets_subnets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/tenortim/isi_sdk_go/models"
)

// CreatePoolsPoolRuleReader is a Reader for the CreatePoolsPoolRule structure.
type CreatePoolsPoolRuleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreatePoolsPoolRuleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCreatePoolsPoolRuleOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewCreatePoolsPoolRuleDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCreatePoolsPoolRuleOK creates a CreatePoolsPoolRuleOK with default headers values
func NewCreatePoolsPoolRuleOK() *CreatePoolsPoolRuleOK {
	return &CreatePoolsPoolRuleOK{}
}

/*CreatePoolsPoolRuleOK handles this case with default header values.

Create a new rule.
*/
type CreatePoolsPoolRuleOK struct {
	Payload *models.CreateResponse
}

func (o *CreatePoolsPoolRuleOK) Error() string {
	return fmt.Sprintf("[POST /platform/3/network/groupnets/{Groupnet}/subnets/{Subnet}/pools/{Pool}/rules][%d] createPoolsPoolRuleOK  %+v", 200, o.Payload)
}

func (o *CreatePoolsPoolRuleOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CreateResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreatePoolsPoolRuleDefault creates a CreatePoolsPoolRuleDefault with default headers values
func NewCreatePoolsPoolRuleDefault(code int) *CreatePoolsPoolRuleDefault {
	return &CreatePoolsPoolRuleDefault{
		_statusCode: code,
	}
}

/*CreatePoolsPoolRuleDefault handles this case with default header values.

Unexpected error
*/
type CreatePoolsPoolRuleDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the create pools pool rule default response
func (o *CreatePoolsPoolRuleDefault) Code() int {
	return o._statusCode
}

func (o *CreatePoolsPoolRuleDefault) Error() string {
	return fmt.Sprintf("[POST /platform/3/network/groupnets/{Groupnet}/subnets/{Subnet}/pools/{Pool}/rules][%d] createPoolsPoolRule default  %+v", o._statusCode, o.Payload)
}

func (o *CreatePoolsPoolRuleDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
