// Code generated by go-swagger; DO NOT EDIT.

package network_groupnets_subnets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/tenortim/isi_sdk_go/models"
)

// NewCreatePoolsPoolRuleParams creates a new CreatePoolsPoolRuleParams object
// with the default values initialized.
func NewCreatePoolsPoolRuleParams() *CreatePoolsPoolRuleParams {
	var ()
	return &CreatePoolsPoolRuleParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreatePoolsPoolRuleParamsWithTimeout creates a new CreatePoolsPoolRuleParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreatePoolsPoolRuleParamsWithTimeout(timeout time.Duration) *CreatePoolsPoolRuleParams {
	var ()
	return &CreatePoolsPoolRuleParams{

		timeout: timeout,
	}
}

// NewCreatePoolsPoolRuleParamsWithContext creates a new CreatePoolsPoolRuleParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreatePoolsPoolRuleParamsWithContext(ctx context.Context) *CreatePoolsPoolRuleParams {
	var ()
	return &CreatePoolsPoolRuleParams{

		Context: ctx,
	}
}

// NewCreatePoolsPoolRuleParamsWithHTTPClient creates a new CreatePoolsPoolRuleParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreatePoolsPoolRuleParamsWithHTTPClient(client *http.Client) *CreatePoolsPoolRuleParams {
	var ()
	return &CreatePoolsPoolRuleParams{
		HTTPClient: client,
	}
}

/*CreatePoolsPoolRuleParams contains all the parameters to send to the API endpoint
for the create pools pool rule operation typically these are written to a http.Request
*/
type CreatePoolsPoolRuleParams struct {

	/*Groupnet*/
	Groupnet string
	/*Pool*/
	Pool string
	/*PoolsPoolRule*/
	PoolsPoolRule *models.PoolsPoolRuleCreateParams
	/*Subnet*/
	Subnet string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create pools pool rule params
func (o *CreatePoolsPoolRuleParams) WithTimeout(timeout time.Duration) *CreatePoolsPoolRuleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create pools pool rule params
func (o *CreatePoolsPoolRuleParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create pools pool rule params
func (o *CreatePoolsPoolRuleParams) WithContext(ctx context.Context) *CreatePoolsPoolRuleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create pools pool rule params
func (o *CreatePoolsPoolRuleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create pools pool rule params
func (o *CreatePoolsPoolRuleParams) WithHTTPClient(client *http.Client) *CreatePoolsPoolRuleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create pools pool rule params
func (o *CreatePoolsPoolRuleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithGroupnet adds the groupnet to the create pools pool rule params
func (o *CreatePoolsPoolRuleParams) WithGroupnet(groupnet string) *CreatePoolsPoolRuleParams {
	o.SetGroupnet(groupnet)
	return o
}

// SetGroupnet adds the groupnet to the create pools pool rule params
func (o *CreatePoolsPoolRuleParams) SetGroupnet(groupnet string) {
	o.Groupnet = groupnet
}

// WithPool adds the pool to the create pools pool rule params
func (o *CreatePoolsPoolRuleParams) WithPool(pool string) *CreatePoolsPoolRuleParams {
	o.SetPool(pool)
	return o
}

// SetPool adds the pool to the create pools pool rule params
func (o *CreatePoolsPoolRuleParams) SetPool(pool string) {
	o.Pool = pool
}

// WithPoolsPoolRule adds the poolsPoolRule to the create pools pool rule params
func (o *CreatePoolsPoolRuleParams) WithPoolsPoolRule(poolsPoolRule *models.PoolsPoolRuleCreateParams) *CreatePoolsPoolRuleParams {
	o.SetPoolsPoolRule(poolsPoolRule)
	return o
}

// SetPoolsPoolRule adds the poolsPoolRule to the create pools pool rule params
func (o *CreatePoolsPoolRuleParams) SetPoolsPoolRule(poolsPoolRule *models.PoolsPoolRuleCreateParams) {
	o.PoolsPoolRule = poolsPoolRule
}

// WithSubnet adds the subnet to the create pools pool rule params
func (o *CreatePoolsPoolRuleParams) WithSubnet(subnet string) *CreatePoolsPoolRuleParams {
	o.SetSubnet(subnet)
	return o
}

// SetSubnet adds the subnet to the create pools pool rule params
func (o *CreatePoolsPoolRuleParams) SetSubnet(subnet string) {
	o.Subnet = subnet
}

// WriteToRequest writes these params to a swagger request
func (o *CreatePoolsPoolRuleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param Groupnet
	if err := r.SetPathParam("Groupnet", o.Groupnet); err != nil {
		return err
	}

	// path param Pool
	if err := r.SetPathParam("Pool", o.Pool); err != nil {
		return err
	}

	if o.PoolsPoolRule != nil {
		if err := r.SetBodyParam(o.PoolsPoolRule); err != nil {
			return err
		}
	}

	// path param Subnet
	if err := r.SetPathParam("Subnet", o.Subnet); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
