// Code generated by go-swagger; DO NOT EDIT.

package network

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/tenortim/isi_sdk_go/models"
)

// NewUpdateNetworkExternalParams creates a new UpdateNetworkExternalParams object
// with the default values initialized.
func NewUpdateNetworkExternalParams() *UpdateNetworkExternalParams {
	var ()
	return &UpdateNetworkExternalParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateNetworkExternalParamsWithTimeout creates a new UpdateNetworkExternalParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateNetworkExternalParamsWithTimeout(timeout time.Duration) *UpdateNetworkExternalParams {
	var ()
	return &UpdateNetworkExternalParams{

		timeout: timeout,
	}
}

// NewUpdateNetworkExternalParamsWithContext creates a new UpdateNetworkExternalParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateNetworkExternalParamsWithContext(ctx context.Context) *UpdateNetworkExternalParams {
	var ()
	return &UpdateNetworkExternalParams{

		Context: ctx,
	}
}

// NewUpdateNetworkExternalParamsWithHTTPClient creates a new UpdateNetworkExternalParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateNetworkExternalParamsWithHTTPClient(client *http.Client) *UpdateNetworkExternalParams {
	var ()
	return &UpdateNetworkExternalParams{
		HTTPClient: client,
	}
}

/*UpdateNetworkExternalParams contains all the parameters to send to the API endpoint
for the update network external operation typically these are written to a http.Request
*/
type UpdateNetworkExternalParams struct {

	/*NetworkExternal*/
	NetworkExternal *models.NetworkExternalExtended

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update network external params
func (o *UpdateNetworkExternalParams) WithTimeout(timeout time.Duration) *UpdateNetworkExternalParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update network external params
func (o *UpdateNetworkExternalParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update network external params
func (o *UpdateNetworkExternalParams) WithContext(ctx context.Context) *UpdateNetworkExternalParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update network external params
func (o *UpdateNetworkExternalParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update network external params
func (o *UpdateNetworkExternalParams) WithHTTPClient(client *http.Client) *UpdateNetworkExternalParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update network external params
func (o *UpdateNetworkExternalParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithNetworkExternal adds the networkExternal to the update network external params
func (o *UpdateNetworkExternalParams) WithNetworkExternal(networkExternal *models.NetworkExternalExtended) *UpdateNetworkExternalParams {
	o.SetNetworkExternal(networkExternal)
	return o
}

// SetNetworkExternal adds the networkExternal to the update network external params
func (o *UpdateNetworkExternalParams) SetNetworkExternal(networkExternal *models.NetworkExternalExtended) {
	o.NetworkExternal = networkExternal
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateNetworkExternalParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.NetworkExternal != nil {
		if err := r.SetBodyParam(o.NetworkExternal); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
