// Code generated by go-swagger; DO NOT EDIT.

package cluster_nodes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/tenortim/isi_sdk_go/models"
)

// NewCreateDrivesDriveSmartfailItemParams creates a new CreateDrivesDriveSmartfailItemParams object
// with the default values initialized.
func NewCreateDrivesDriveSmartfailItemParams() *CreateDrivesDriveSmartfailItemParams {
	var ()
	return &CreateDrivesDriveSmartfailItemParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateDrivesDriveSmartfailItemParamsWithTimeout creates a new CreateDrivesDriveSmartfailItemParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateDrivesDriveSmartfailItemParamsWithTimeout(timeout time.Duration) *CreateDrivesDriveSmartfailItemParams {
	var ()
	return &CreateDrivesDriveSmartfailItemParams{

		timeout: timeout,
	}
}

// NewCreateDrivesDriveSmartfailItemParamsWithContext creates a new CreateDrivesDriveSmartfailItemParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateDrivesDriveSmartfailItemParamsWithContext(ctx context.Context) *CreateDrivesDriveSmartfailItemParams {
	var ()
	return &CreateDrivesDriveSmartfailItemParams{

		Context: ctx,
	}
}

// NewCreateDrivesDriveSmartfailItemParamsWithHTTPClient creates a new CreateDrivesDriveSmartfailItemParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateDrivesDriveSmartfailItemParamsWithHTTPClient(client *http.Client) *CreateDrivesDriveSmartfailItemParams {
	var ()
	return &CreateDrivesDriveSmartfailItemParams{
		HTTPClient: client,
	}
}

/*CreateDrivesDriveSmartfailItemParams contains all the parameters to send to the API endpoint
for the create drives drive smartfail item operation typically these are written to a http.Request
*/
type CreateDrivesDriveSmartfailItemParams struct {

	/*Driveid*/
	Driveid string
	/*DrivesDriveSmartfailItem*/
	DrivesDriveSmartfailItem models.Empty
	/*Lnn*/
	Lnn int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create drives drive smartfail item params
func (o *CreateDrivesDriveSmartfailItemParams) WithTimeout(timeout time.Duration) *CreateDrivesDriveSmartfailItemParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create drives drive smartfail item params
func (o *CreateDrivesDriveSmartfailItemParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create drives drive smartfail item params
func (o *CreateDrivesDriveSmartfailItemParams) WithContext(ctx context.Context) *CreateDrivesDriveSmartfailItemParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create drives drive smartfail item params
func (o *CreateDrivesDriveSmartfailItemParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create drives drive smartfail item params
func (o *CreateDrivesDriveSmartfailItemParams) WithHTTPClient(client *http.Client) *CreateDrivesDriveSmartfailItemParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create drives drive smartfail item params
func (o *CreateDrivesDriveSmartfailItemParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDriveid adds the driveid to the create drives drive smartfail item params
func (o *CreateDrivesDriveSmartfailItemParams) WithDriveid(driveid string) *CreateDrivesDriveSmartfailItemParams {
	o.SetDriveid(driveid)
	return o
}

// SetDriveid adds the driveid to the create drives drive smartfail item params
func (o *CreateDrivesDriveSmartfailItemParams) SetDriveid(driveid string) {
	o.Driveid = driveid
}

// WithDrivesDriveSmartfailItem adds the drivesDriveSmartfailItem to the create drives drive smartfail item params
func (o *CreateDrivesDriveSmartfailItemParams) WithDrivesDriveSmartfailItem(drivesDriveSmartfailItem models.Empty) *CreateDrivesDriveSmartfailItemParams {
	o.SetDrivesDriveSmartfailItem(drivesDriveSmartfailItem)
	return o
}

// SetDrivesDriveSmartfailItem adds the drivesDriveSmartfailItem to the create drives drive smartfail item params
func (o *CreateDrivesDriveSmartfailItemParams) SetDrivesDriveSmartfailItem(drivesDriveSmartfailItem models.Empty) {
	o.DrivesDriveSmartfailItem = drivesDriveSmartfailItem
}

// WithLnn adds the lnn to the create drives drive smartfail item params
func (o *CreateDrivesDriveSmartfailItemParams) WithLnn(lnn int64) *CreateDrivesDriveSmartfailItemParams {
	o.SetLnn(lnn)
	return o
}

// SetLnn adds the lnn to the create drives drive smartfail item params
func (o *CreateDrivesDriveSmartfailItemParams) SetLnn(lnn int64) {
	o.Lnn = lnn
}

// WriteToRequest writes these params to a swagger request
func (o *CreateDrivesDriveSmartfailItemParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param Driveid
	if err := r.SetPathParam("Driveid", o.Driveid); err != nil {
		return err
	}

	if o.DrivesDriveSmartfailItem != nil {
		if err := r.SetBodyParam(o.DrivesDriveSmartfailItem); err != nil {
			return err
		}
	}

	// path param Lnn
	if err := r.SetPathParam("Lnn", swag.FormatInt64(o.Lnn)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
