// Code generated by go-swagger; DO NOT EDIT.

package cluster_nodes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/tenortim/isi_sdk_go/models"
)

// CreateDrivesDriveStopfailItemReader is a Reader for the CreateDrivesDriveStopfailItem structure.
type CreateDrivesDriveStopfailItemReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateDrivesDriveStopfailItemReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCreateDrivesDriveStopfailItemOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewCreateDrivesDriveStopfailItemDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCreateDrivesDriveStopfailItemOK creates a CreateDrivesDriveStopfailItemOK with default headers values
func NewCreateDrivesDriveStopfailItemOK() *CreateDrivesDriveStopfailItemOK {
	return &CreateDrivesDriveStopfailItemOK{}
}

/*CreateDrivesDriveStopfailItemOK handles this case with default header values.

Stop restriping from a smartfailing drive.
*/
type CreateDrivesDriveStopfailItemOK struct {
	Payload models.Empty
}

func (o *CreateDrivesDriveStopfailItemOK) Error() string {
	return fmt.Sprintf("[POST /platform/3/cluster/nodes/{Lnn}/drives/{Driveid}/stopfail][%d] createDrivesDriveStopfailItemOK  %+v", 200, o.Payload)
}

func (o *CreateDrivesDriveStopfailItemOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateDrivesDriveStopfailItemDefault creates a CreateDrivesDriveStopfailItemDefault with default headers values
func NewCreateDrivesDriveStopfailItemDefault(code int) *CreateDrivesDriveStopfailItemDefault {
	return &CreateDrivesDriveStopfailItemDefault{
		_statusCode: code,
	}
}

/*CreateDrivesDriveStopfailItemDefault handles this case with default header values.

Unexpected error
*/
type CreateDrivesDriveStopfailItemDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the create drives drive stopfail item default response
func (o *CreateDrivesDriveStopfailItemDefault) Code() int {
	return o._statusCode
}

func (o *CreateDrivesDriveStopfailItemDefault) Error() string {
	return fmt.Sprintf("[POST /platform/3/cluster/nodes/{Lnn}/drives/{Driveid}/stopfail][%d] createDrivesDriveStopfailItem default  %+v", o._statusCode, o.Payload)
}

func (o *CreateDrivesDriveStopfailItemDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
