// Code generated by go-swagger; DO NOT EDIT.

package cluster_nodes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetNodePartitionsParams creates a new GetNodePartitionsParams object
// with the default values initialized.
func NewGetNodePartitionsParams() *GetNodePartitionsParams {
	var ()
	return &GetNodePartitionsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetNodePartitionsParamsWithTimeout creates a new GetNodePartitionsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetNodePartitionsParamsWithTimeout(timeout time.Duration) *GetNodePartitionsParams {
	var ()
	return &GetNodePartitionsParams{

		timeout: timeout,
	}
}

// NewGetNodePartitionsParamsWithContext creates a new GetNodePartitionsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetNodePartitionsParamsWithContext(ctx context.Context) *GetNodePartitionsParams {
	var ()
	return &GetNodePartitionsParams{

		Context: ctx,
	}
}

// NewGetNodePartitionsParamsWithHTTPClient creates a new GetNodePartitionsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetNodePartitionsParamsWithHTTPClient(client *http.Client) *GetNodePartitionsParams {
	var ()
	return &GetNodePartitionsParams{
		HTTPClient: client,
	}
}

/*GetNodePartitionsParams contains all the parameters to send to the API endpoint
for the get node partitions operation typically these are written to a http.Request
*/
type GetNodePartitionsParams struct {

	/*Lnn*/
	Lnn int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get node partitions params
func (o *GetNodePartitionsParams) WithTimeout(timeout time.Duration) *GetNodePartitionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get node partitions params
func (o *GetNodePartitionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get node partitions params
func (o *GetNodePartitionsParams) WithContext(ctx context.Context) *GetNodePartitionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get node partitions params
func (o *GetNodePartitionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get node partitions params
func (o *GetNodePartitionsParams) WithHTTPClient(client *http.Client) *GetNodePartitionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get node partitions params
func (o *GetNodePartitionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLnn adds the lnn to the get node partitions params
func (o *GetNodePartitionsParams) WithLnn(lnn int64) *GetNodePartitionsParams {
	o.SetLnn(lnn)
	return o
}

// SetLnn adds the lnn to the get node partitions params
func (o *GetNodePartitionsParams) SetLnn(lnn int64) {
	o.Lnn = lnn
}

// WriteToRequest writes these params to a swagger request
func (o *GetNodePartitionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param Lnn
	if err := r.SetPathParam("Lnn", swag.FormatInt64(o.Lnn)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
