// Code generated by go-swagger; DO NOT EDIT.

package snapshot

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/tenortim/isi_sdk_go/models"
)

// CreateSnapshotScheduleReader is a Reader for the CreateSnapshotSchedule structure.
type CreateSnapshotScheduleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateSnapshotScheduleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCreateSnapshotScheduleOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewCreateSnapshotScheduleDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCreateSnapshotScheduleOK creates a CreateSnapshotScheduleOK with default headers values
func NewCreateSnapshotScheduleOK() *CreateSnapshotScheduleOK {
	return &CreateSnapshotScheduleOK{}
}

/*CreateSnapshotScheduleOK handles this case with default header values.

Create a new schedule.
*/
type CreateSnapshotScheduleOK struct {
	Payload *models.CreateSnapshotScheduleResponse
}

func (o *CreateSnapshotScheduleOK) Error() string {
	return fmt.Sprintf("[POST /platform/3/snapshot/schedules][%d] createSnapshotScheduleOK  %+v", 200, o.Payload)
}

func (o *CreateSnapshotScheduleOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CreateSnapshotScheduleResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateSnapshotScheduleDefault creates a CreateSnapshotScheduleDefault with default headers values
func NewCreateSnapshotScheduleDefault(code int) *CreateSnapshotScheduleDefault {
	return &CreateSnapshotScheduleDefault{
		_statusCode: code,
	}
}

/*CreateSnapshotScheduleDefault handles this case with default header values.

Unexpected error
*/
type CreateSnapshotScheduleDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the create snapshot schedule default response
func (o *CreateSnapshotScheduleDefault) Code() int {
	return o._statusCode
}

func (o *CreateSnapshotScheduleDefault) Error() string {
	return fmt.Sprintf("[POST /platform/3/snapshot/schedules][%d] createSnapshotSchedule default  %+v", o._statusCode, o.Payload)
}

func (o *CreateSnapshotScheduleDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
