// Code generated by go-swagger; DO NOT EDIT.

package snapshot

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/tenortim/isi_sdk_go/models"
)

// DeleteSnapshotAliasesReader is a Reader for the DeleteSnapshotAliases structure.
type DeleteSnapshotAliasesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteSnapshotAliasesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDeleteSnapshotAliasesNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewDeleteSnapshotAliasesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteSnapshotAliasesNoContent creates a DeleteSnapshotAliasesNoContent with default headers values
func NewDeleteSnapshotAliasesNoContent() *DeleteSnapshotAliasesNoContent {
	return &DeleteSnapshotAliasesNoContent{}
}

/*DeleteSnapshotAliasesNoContent handles this case with default header values.

Success.
*/
type DeleteSnapshotAliasesNoContent struct {
}

func (o *DeleteSnapshotAliasesNoContent) Error() string {
	return fmt.Sprintf("[DELETE /platform/1/snapshot/aliases][%d] deleteSnapshotAliasesNoContent ", 204)
}

func (o *DeleteSnapshotAliasesNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteSnapshotAliasesDefault creates a DeleteSnapshotAliasesDefault with default headers values
func NewDeleteSnapshotAliasesDefault(code int) *DeleteSnapshotAliasesDefault {
	return &DeleteSnapshotAliasesDefault{
		_statusCode: code,
	}
}

/*DeleteSnapshotAliasesDefault handles this case with default header values.

Unexpected error
*/
type DeleteSnapshotAliasesDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the delete snapshot aliases default response
func (o *DeleteSnapshotAliasesDefault) Code() int {
	return o._statusCode
}

func (o *DeleteSnapshotAliasesDefault) Error() string {
	return fmt.Sprintf("[DELETE /platform/1/snapshot/aliases][%d] deleteSnapshotAliases default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteSnapshotAliasesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
