// Code generated by go-swagger; DO NOT EDIT.

package statistics

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/tenortim/isi_sdk_go/models"
)

// GetStatisticsProtocolsReader is a Reader for the GetStatisticsProtocols structure.
type GetStatisticsProtocolsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetStatisticsProtocolsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetStatisticsProtocolsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetStatisticsProtocolsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetStatisticsProtocolsOK creates a GetStatisticsProtocolsOK with default headers values
func NewGetStatisticsProtocolsOK() *GetStatisticsProtocolsOK {
	return &GetStatisticsProtocolsOK{}
}

/*GetStatisticsProtocolsOK handles this case with default header values.

Retrieve protocol list.
*/
type GetStatisticsProtocolsOK struct {
	Payload *models.StatisticsProtocols
}

func (o *GetStatisticsProtocolsOK) Error() string {
	return fmt.Sprintf("[GET /platform/1/statistics/protocols][%d] getStatisticsProtocolsOK  %+v", 200, o.Payload)
}

func (o *GetStatisticsProtocolsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StatisticsProtocols)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetStatisticsProtocolsDefault creates a GetStatisticsProtocolsDefault with default headers values
func NewGetStatisticsProtocolsDefault(code int) *GetStatisticsProtocolsDefault {
	return &GetStatisticsProtocolsDefault{
		_statusCode: code,
	}
}

/*GetStatisticsProtocolsDefault handles this case with default header values.

Unexpected error
*/
type GetStatisticsProtocolsDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get statistics protocols default response
func (o *GetStatisticsProtocolsDefault) Code() int {
	return o._statusCode
}

func (o *GetStatisticsProtocolsDefault) Error() string {
	return fmt.Sprintf("[GET /platform/1/statistics/protocols][%d] getStatisticsProtocols default  %+v", o._statusCode, o.Payload)
}

func (o *GetStatisticsProtocolsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
