// Code generated by go-swagger; DO NOT EDIT.

package worm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetWormSettingsParams creates a new GetWormSettingsParams object
// with the default values initialized.
func NewGetWormSettingsParams() *GetWormSettingsParams {

	return &GetWormSettingsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetWormSettingsParamsWithTimeout creates a new GetWormSettingsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetWormSettingsParamsWithTimeout(timeout time.Duration) *GetWormSettingsParams {

	return &GetWormSettingsParams{

		timeout: timeout,
	}
}

// NewGetWormSettingsParamsWithContext creates a new GetWormSettingsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetWormSettingsParamsWithContext(ctx context.Context) *GetWormSettingsParams {

	return &GetWormSettingsParams{

		Context: ctx,
	}
}

// NewGetWormSettingsParamsWithHTTPClient creates a new GetWormSettingsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetWormSettingsParamsWithHTTPClient(client *http.Client) *GetWormSettingsParams {

	return &GetWormSettingsParams{
		HTTPClient: client,
	}
}

/*GetWormSettingsParams contains all the parameters to send to the API endpoint
for the get worm settings operation typically these are written to a http.Request
*/
type GetWormSettingsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get worm settings params
func (o *GetWormSettingsParams) WithTimeout(timeout time.Duration) *GetWormSettingsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get worm settings params
func (o *GetWormSettingsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get worm settings params
func (o *GetWormSettingsParams) WithContext(ctx context.Context) *GetWormSettingsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get worm settings params
func (o *GetWormSettingsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get worm settings params
func (o *GetWormSettingsParams) WithHTTPClient(client *http.Client) *GetWormSettingsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get worm settings params
func (o *GetWormSettingsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetWormSettingsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
