// Code generated by go-swagger; DO NOT EDIT.

package sync

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/tenortim/isi_sdk_go/models"
)

// GetSyncJobReader is a Reader for the GetSyncJob structure.
type GetSyncJobReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSyncJobReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetSyncJobOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetSyncJobDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetSyncJobOK creates a GetSyncJobOK with default headers values
func NewGetSyncJobOK() *GetSyncJobOK {
	return &GetSyncJobOK{}
}

/*GetSyncJobOK handles this case with default header values.

View a single SyncIQ job.
*/
type GetSyncJobOK struct {
	Payload *models.SyncJobs
}

func (o *GetSyncJobOK) Error() string {
	return fmt.Sprintf("[GET /platform/3/sync/jobs/{SyncJobId}][%d] getSyncJobOK  %+v", 200, o.Payload)
}

func (o *GetSyncJobOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SyncJobs)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSyncJobDefault creates a GetSyncJobDefault with default headers values
func NewGetSyncJobDefault(code int) *GetSyncJobDefault {
	return &GetSyncJobDefault{
		_statusCode: code,
	}
}

/*GetSyncJobDefault handles this case with default header values.

Unexpected error
*/
type GetSyncJobDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get sync job default response
func (o *GetSyncJobDefault) Code() int {
	return o._statusCode
}

func (o *GetSyncJobDefault) Error() string {
	return fmt.Sprintf("[GET /platform/3/sync/jobs/{SyncJobId}][%d] getSyncJob default  %+v", o._statusCode, o.Payload)
}

func (o *GetSyncJobDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
