// Code generated by go-swagger; DO NOT EDIT.

package sync

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/tenortim/isi_sdk_go/models"
)

// UpdateSyncSettingsReader is a Reader for the UpdateSyncSettings structure.
type UpdateSyncSettingsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateSyncSettingsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewUpdateSyncSettingsNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewUpdateSyncSettingsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewUpdateSyncSettingsNoContent creates a UpdateSyncSettingsNoContent with default headers values
func NewUpdateSyncSettingsNoContent() *UpdateSyncSettingsNoContent {
	return &UpdateSyncSettingsNoContent{}
}

/*UpdateSyncSettingsNoContent handles this case with default header values.

Success.
*/
type UpdateSyncSettingsNoContent struct {
}

func (o *UpdateSyncSettingsNoContent) Error() string {
	return fmt.Sprintf("[PUT /platform/3/sync/settings][%d] updateSyncSettingsNoContent ", 204)
}

func (o *UpdateSyncSettingsNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateSyncSettingsDefault creates a UpdateSyncSettingsDefault with default headers values
func NewUpdateSyncSettingsDefault(code int) *UpdateSyncSettingsDefault {
	return &UpdateSyncSettingsDefault{
		_statusCode: code,
	}
}

/*UpdateSyncSettingsDefault handles this case with default header values.

Unexpected error
*/
type UpdateSyncSettingsDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the update sync settings default response
func (o *UpdateSyncSettingsDefault) Code() int {
	return o._statusCode
}

func (o *UpdateSyncSettingsDefault) Error() string {
	return fmt.Sprintf("[PUT /platform/3/sync/settings][%d] updateSyncSettings default  %+v", o._statusCode, o.Payload)
}

func (o *UpdateSyncSettingsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
