// Code generated by go-swagger; DO NOT EDIT.

package audit

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/tenortim/isi_sdk_go/models"
)

// NewCreateAuditTopicParams creates a new CreateAuditTopicParams object
// with the default values initialized.
func NewCreateAuditTopicParams() *CreateAuditTopicParams {
	var ()
	return &CreateAuditTopicParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateAuditTopicParamsWithTimeout creates a new CreateAuditTopicParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateAuditTopicParamsWithTimeout(timeout time.Duration) *CreateAuditTopicParams {
	var ()
	return &CreateAuditTopicParams{

		timeout: timeout,
	}
}

// NewCreateAuditTopicParamsWithContext creates a new CreateAuditTopicParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateAuditTopicParamsWithContext(ctx context.Context) *CreateAuditTopicParams {
	var ()
	return &CreateAuditTopicParams{

		Context: ctx,
	}
}

// NewCreateAuditTopicParamsWithHTTPClient creates a new CreateAuditTopicParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateAuditTopicParamsWithHTTPClient(client *http.Client) *CreateAuditTopicParams {
	var ()
	return &CreateAuditTopicParams{
		HTTPClient: client,
	}
}

/*CreateAuditTopicParams contains all the parameters to send to the API endpoint
for the create audit topic operation typically these are written to a http.Request
*/
type CreateAuditTopicParams struct {

	/*AuditTopic*/
	AuditTopic *models.AuditTopicCreateParams

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create audit topic params
func (o *CreateAuditTopicParams) WithTimeout(timeout time.Duration) *CreateAuditTopicParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create audit topic params
func (o *CreateAuditTopicParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create audit topic params
func (o *CreateAuditTopicParams) WithContext(ctx context.Context) *CreateAuditTopicParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create audit topic params
func (o *CreateAuditTopicParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create audit topic params
func (o *CreateAuditTopicParams) WithHTTPClient(client *http.Client) *CreateAuditTopicParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create audit topic params
func (o *CreateAuditTopicParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuditTopic adds the auditTopic to the create audit topic params
func (o *CreateAuditTopicParams) WithAuditTopic(auditTopic *models.AuditTopicCreateParams) *CreateAuditTopicParams {
	o.SetAuditTopic(auditTopic)
	return o
}

// SetAuditTopic adds the auditTopic to the create audit topic params
func (o *CreateAuditTopicParams) SetAuditTopic(auditTopic *models.AuditTopicCreateParams) {
	o.AuditTopic = auditTopic
}

// WriteToRequest writes these params to a swagger request
func (o *CreateAuditTopicParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.AuditTopic != nil {
		if err := r.SetBodyParam(o.AuditTopic); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
