// Code generated by go-swagger; DO NOT EDIT.

package audit

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetSettingsGlobalParams creates a new GetSettingsGlobalParams object
// with the default values initialized.
func NewGetSettingsGlobalParams() *GetSettingsGlobalParams {

	return &GetSettingsGlobalParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetSettingsGlobalParamsWithTimeout creates a new GetSettingsGlobalParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetSettingsGlobalParamsWithTimeout(timeout time.Duration) *GetSettingsGlobalParams {

	return &GetSettingsGlobalParams{

		timeout: timeout,
	}
}

// NewGetSettingsGlobalParamsWithContext creates a new GetSettingsGlobalParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetSettingsGlobalParamsWithContext(ctx context.Context) *GetSettingsGlobalParams {

	return &GetSettingsGlobalParams{

		Context: ctx,
	}
}

// NewGetSettingsGlobalParamsWithHTTPClient creates a new GetSettingsGlobalParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetSettingsGlobalParamsWithHTTPClient(client *http.Client) *GetSettingsGlobalParams {

	return &GetSettingsGlobalParams{
		HTTPClient: client,
	}
}

/*GetSettingsGlobalParams contains all the parameters to send to the API endpoint
for the get settings global operation typically these are written to a http.Request
*/
type GetSettingsGlobalParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get settings global params
func (o *GetSettingsGlobalParams) WithTimeout(timeout time.Duration) *GetSettingsGlobalParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get settings global params
func (o *GetSettingsGlobalParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get settings global params
func (o *GetSettingsGlobalParams) WithContext(ctx context.Context) *GetSettingsGlobalParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get settings global params
func (o *GetSettingsGlobalParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get settings global params
func (o *GetSettingsGlobalParams) WithHTTPClient(client *http.Client) *GetSettingsGlobalParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get settings global params
func (o *GetSettingsGlobalParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetSettingsGlobalParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
