// Code generated by go-swagger; DO NOT EDIT.

package audit

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/tenortim/isi_sdk_go/models"
)

// GetAuditSettingsReader is a Reader for the GetAuditSettings structure.
type GetAuditSettingsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAuditSettingsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAuditSettingsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetAuditSettingsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetAuditSettingsOK creates a GetAuditSettingsOK with default headers values
func NewGetAuditSettingsOK() *GetAuditSettingsOK {
	return &GetAuditSettingsOK{}
}

/*GetAuditSettingsOK handles this case with default header values.

View per-Access Zone Audit settings.
*/
type GetAuditSettingsOK struct {
	Payload *models.AuditSettings
}

func (o *GetAuditSettingsOK) Error() string {
	return fmt.Sprintf("[GET /platform/3/audit/settings][%d] getAuditSettingsOK  %+v", 200, o.Payload)
}

func (o *GetAuditSettingsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AuditSettings)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAuditSettingsDefault creates a GetAuditSettingsDefault with default headers values
func NewGetAuditSettingsDefault(code int) *GetAuditSettingsDefault {
	return &GetAuditSettingsDefault{
		_statusCode: code,
	}
}

/*GetAuditSettingsDefault handles this case with default header values.

Unexpected error
*/
type GetAuditSettingsDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get audit settings default response
func (o *GetAuditSettingsDefault) Code() int {
	return o._statusCode
}

func (o *GetAuditSettingsDefault) Error() string {
	return fmt.Sprintf("[GET /platform/3/audit/settings][%d] getAuditSettings default  %+v", o._statusCode, o.Payload)
}

func (o *GetAuditSettingsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
