// Code generated by go-swagger; DO NOT EDIT.

package job

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetJobStatisticsParams creates a new GetJobStatisticsParams object
// with the default values initialized.
func NewGetJobStatisticsParams() *GetJobStatisticsParams {

	return &GetJobStatisticsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetJobStatisticsParamsWithTimeout creates a new GetJobStatisticsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetJobStatisticsParamsWithTimeout(timeout time.Duration) *GetJobStatisticsParams {

	return &GetJobStatisticsParams{

		timeout: timeout,
	}
}

// NewGetJobStatisticsParamsWithContext creates a new GetJobStatisticsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetJobStatisticsParamsWithContext(ctx context.Context) *GetJobStatisticsParams {

	return &GetJobStatisticsParams{

		Context: ctx,
	}
}

// NewGetJobStatisticsParamsWithHTTPClient creates a new GetJobStatisticsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetJobStatisticsParamsWithHTTPClient(client *http.Client) *GetJobStatisticsParams {

	return &GetJobStatisticsParams{
		HTTPClient: client,
	}
}

/*GetJobStatisticsParams contains all the parameters to send to the API endpoint
for the get job statistics operation typically these are written to a http.Request
*/
type GetJobStatisticsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get job statistics params
func (o *GetJobStatisticsParams) WithTimeout(timeout time.Duration) *GetJobStatisticsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get job statistics params
func (o *GetJobStatisticsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get job statistics params
func (o *GetJobStatisticsParams) WithContext(ctx context.Context) *GetJobStatisticsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get job statistics params
func (o *GetJobStatisticsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get job statistics params
func (o *GetJobStatisticsParams) WithHTTPClient(client *http.Client) *GetJobStatisticsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get job statistics params
func (o *GetJobStatisticsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetJobStatisticsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
