// Code generated by go-swagger; DO NOT EDIT.

package protocols

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/tenortim/isi_sdk_go/models"
)

// NewCreateNfsNetgroupFlushItemParams creates a new CreateNfsNetgroupFlushItemParams object
// with the default values initialized.
func NewCreateNfsNetgroupFlushItemParams() *CreateNfsNetgroupFlushItemParams {
	var ()
	return &CreateNfsNetgroupFlushItemParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateNfsNetgroupFlushItemParamsWithTimeout creates a new CreateNfsNetgroupFlushItemParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateNfsNetgroupFlushItemParamsWithTimeout(timeout time.Duration) *CreateNfsNetgroupFlushItemParams {
	var ()
	return &CreateNfsNetgroupFlushItemParams{

		timeout: timeout,
	}
}

// NewCreateNfsNetgroupFlushItemParamsWithContext creates a new CreateNfsNetgroupFlushItemParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateNfsNetgroupFlushItemParamsWithContext(ctx context.Context) *CreateNfsNetgroupFlushItemParams {
	var ()
	return &CreateNfsNetgroupFlushItemParams{

		Context: ctx,
	}
}

// NewCreateNfsNetgroupFlushItemParamsWithHTTPClient creates a new CreateNfsNetgroupFlushItemParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateNfsNetgroupFlushItemParamsWithHTTPClient(client *http.Client) *CreateNfsNetgroupFlushItemParams {
	var ()
	return &CreateNfsNetgroupFlushItemParams{
		HTTPClient: client,
	}
}

/*CreateNfsNetgroupFlushItemParams contains all the parameters to send to the API endpoint
for the create nfs netgroup flush item operation typically these are written to a http.Request
*/
type CreateNfsNetgroupFlushItemParams struct {

	/*NfsNetgroupFlushItem*/
	NfsNetgroupFlushItem models.Empty
	/*Host
	  IP address of node to flush. If unspecified, all nodes on the cluster are flushed.

	*/
	Host *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create nfs netgroup flush item params
func (o *CreateNfsNetgroupFlushItemParams) WithTimeout(timeout time.Duration) *CreateNfsNetgroupFlushItemParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create nfs netgroup flush item params
func (o *CreateNfsNetgroupFlushItemParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create nfs netgroup flush item params
func (o *CreateNfsNetgroupFlushItemParams) WithContext(ctx context.Context) *CreateNfsNetgroupFlushItemParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create nfs netgroup flush item params
func (o *CreateNfsNetgroupFlushItemParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create nfs netgroup flush item params
func (o *CreateNfsNetgroupFlushItemParams) WithHTTPClient(client *http.Client) *CreateNfsNetgroupFlushItemParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create nfs netgroup flush item params
func (o *CreateNfsNetgroupFlushItemParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithNfsNetgroupFlushItem adds the nfsNetgroupFlushItem to the create nfs netgroup flush item params
func (o *CreateNfsNetgroupFlushItemParams) WithNfsNetgroupFlushItem(nfsNetgroupFlushItem models.Empty) *CreateNfsNetgroupFlushItemParams {
	o.SetNfsNetgroupFlushItem(nfsNetgroupFlushItem)
	return o
}

// SetNfsNetgroupFlushItem adds the nfsNetgroupFlushItem to the create nfs netgroup flush item params
func (o *CreateNfsNetgroupFlushItemParams) SetNfsNetgroupFlushItem(nfsNetgroupFlushItem models.Empty) {
	o.NfsNetgroupFlushItem = nfsNetgroupFlushItem
}

// WithHost adds the host to the create nfs netgroup flush item params
func (o *CreateNfsNetgroupFlushItemParams) WithHost(host *string) *CreateNfsNetgroupFlushItemParams {
	o.SetHost(host)
	return o
}

// SetHost adds the host to the create nfs netgroup flush item params
func (o *CreateNfsNetgroupFlushItemParams) SetHost(host *string) {
	o.Host = host
}

// WriteToRequest writes these params to a swagger request
func (o *CreateNfsNetgroupFlushItemParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.NfsNetgroupFlushItem != nil {
		if err := r.SetBodyParam(o.NfsNetgroupFlushItem); err != nil {
			return err
		}
	}

	if o.Host != nil {

		// query param host
		var qrHost string
		if o.Host != nil {
			qrHost = *o.Host
		}
		qHost := qrHost
		if qHost != "" {
			if err := r.SetQueryParam("host", qHost); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
