// Code generated by go-swagger; DO NOT EDIT.

package protocols

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/tenortim/isi_sdk_go/models"
)

// NewCreateSmbShareParams creates a new CreateSmbShareParams object
// with the default values initialized.
func NewCreateSmbShareParams() *CreateSmbShareParams {
	var ()
	return &CreateSmbShareParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateSmbShareParamsWithTimeout creates a new CreateSmbShareParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateSmbShareParamsWithTimeout(timeout time.Duration) *CreateSmbShareParams {
	var ()
	return &CreateSmbShareParams{

		timeout: timeout,
	}
}

// NewCreateSmbShareParamsWithContext creates a new CreateSmbShareParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateSmbShareParamsWithContext(ctx context.Context) *CreateSmbShareParams {
	var ()
	return &CreateSmbShareParams{

		Context: ctx,
	}
}

// NewCreateSmbShareParamsWithHTTPClient creates a new CreateSmbShareParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateSmbShareParamsWithHTTPClient(client *http.Client) *CreateSmbShareParams {
	var ()
	return &CreateSmbShareParams{
		HTTPClient: client,
	}
}

/*CreateSmbShareParams contains all the parameters to send to the API endpoint
for the create smb share operation typically these are written to a http.Request
*/
type CreateSmbShareParams struct {

	/*SmbShare*/
	SmbShare *models.SmbShareCreateParams
	/*Zone
	  Zone which contains this share.

	*/
	Zone *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create smb share params
func (o *CreateSmbShareParams) WithTimeout(timeout time.Duration) *CreateSmbShareParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create smb share params
func (o *CreateSmbShareParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create smb share params
func (o *CreateSmbShareParams) WithContext(ctx context.Context) *CreateSmbShareParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create smb share params
func (o *CreateSmbShareParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create smb share params
func (o *CreateSmbShareParams) WithHTTPClient(client *http.Client) *CreateSmbShareParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create smb share params
func (o *CreateSmbShareParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSmbShare adds the smbShare to the create smb share params
func (o *CreateSmbShareParams) WithSmbShare(smbShare *models.SmbShareCreateParams) *CreateSmbShareParams {
	o.SetSmbShare(smbShare)
	return o
}

// SetSmbShare adds the smbShare to the create smb share params
func (o *CreateSmbShareParams) SetSmbShare(smbShare *models.SmbShareCreateParams) {
	o.SmbShare = smbShare
}

// WithZone adds the zone to the create smb share params
func (o *CreateSmbShareParams) WithZone(zone *string) *CreateSmbShareParams {
	o.SetZone(zone)
	return o
}

// SetZone adds the zone to the create smb share params
func (o *CreateSmbShareParams) SetZone(zone *string) {
	o.Zone = zone
}

// WriteToRequest writes these params to a swagger request
func (o *CreateSmbShareParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.SmbShare != nil {
		if err := r.SetBodyParam(o.SmbShare); err != nil {
			return err
		}
	}

	if o.Zone != nil {

		// query param zone
		var qrZone string
		if o.Zone != nil {
			qrZone = *o.Zone
		}
		qZone := qrZone
		if qZone != "" {
			if err := r.SetQueryParam("zone", qZone); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
