// Code generated by go-swagger; DO NOT EDIT.

package protocols

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/tenortim/isi_sdk_go/models"
)

// DeleteNdmpContextsRestoreByIDReader is a Reader for the DeleteNdmpContextsRestoreByID structure.
type DeleteNdmpContextsRestoreByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteNdmpContextsRestoreByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDeleteNdmpContextsRestoreByIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewDeleteNdmpContextsRestoreByIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteNdmpContextsRestoreByIDNoContent creates a DeleteNdmpContextsRestoreByIDNoContent with default headers values
func NewDeleteNdmpContextsRestoreByIDNoContent() *DeleteNdmpContextsRestoreByIDNoContent {
	return &DeleteNdmpContextsRestoreByIDNoContent{}
}

/*DeleteNdmpContextsRestoreByIDNoContent handles this case with default header values.

Success.
*/
type DeleteNdmpContextsRestoreByIDNoContent struct {
}

func (o *DeleteNdmpContextsRestoreByIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /platform/3/protocols/ndmp/contexts/restore/{NdmpContextsRestoreId}][%d] deleteNdmpContextsRestoreByIdNoContent ", 204)
}

func (o *DeleteNdmpContextsRestoreByIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteNdmpContextsRestoreByIDDefault creates a DeleteNdmpContextsRestoreByIDDefault with default headers values
func NewDeleteNdmpContextsRestoreByIDDefault(code int) *DeleteNdmpContextsRestoreByIDDefault {
	return &DeleteNdmpContextsRestoreByIDDefault{
		_statusCode: code,
	}
}

/*DeleteNdmpContextsRestoreByIDDefault handles this case with default header values.

Unexpected error
*/
type DeleteNdmpContextsRestoreByIDDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the delete ndmp contexts restore by Id default response
func (o *DeleteNdmpContextsRestoreByIDDefault) Code() int {
	return o._statusCode
}

func (o *DeleteNdmpContextsRestoreByIDDefault) Error() string {
	return fmt.Sprintf("[DELETE /platform/3/protocols/ndmp/contexts/restore/{NdmpContextsRestoreId}][%d] deleteNdmpContextsRestoreById default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteNdmpContextsRestoreByIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
