// Code generated by go-swagger; DO NOT EDIT.

package protocols

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/tenortim/isi_sdk_go/models"
)

// DeleteHdfsRackReader is a Reader for the DeleteHdfsRack structure.
type DeleteHdfsRackReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteHdfsRackReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDeleteHdfsRackNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewDeleteHdfsRackDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteHdfsRackNoContent creates a DeleteHdfsRackNoContent with default headers values
func NewDeleteHdfsRackNoContent() *DeleteHdfsRackNoContent {
	return &DeleteHdfsRackNoContent{}
}

/*DeleteHdfsRackNoContent handles this case with default header values.

Success.
*/
type DeleteHdfsRackNoContent struct {
}

func (o *DeleteHdfsRackNoContent) Error() string {
	return fmt.Sprintf("[DELETE /platform/1/protocols/hdfs/racks/{HdfsRackId}][%d] deleteHdfsRackNoContent ", 204)
}

func (o *DeleteHdfsRackNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteHdfsRackDefault creates a DeleteHdfsRackDefault with default headers values
func NewDeleteHdfsRackDefault(code int) *DeleteHdfsRackDefault {
	return &DeleteHdfsRackDefault{
		_statusCode: code,
	}
}

/*DeleteHdfsRackDefault handles this case with default header values.

Unexpected error
*/
type DeleteHdfsRackDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the delete hdfs rack default response
func (o *DeleteHdfsRackDefault) Code() int {
	return o._statusCode
}

func (o *DeleteHdfsRackDefault) Error() string {
	return fmt.Sprintf("[DELETE /platform/1/protocols/hdfs/racks/{HdfsRackId}][%d] deleteHdfsRack default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteHdfsRackDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
