// Code generated by go-swagger; DO NOT EDIT.

package protocols

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/tenortim/isi_sdk_go/models"
)

// GetNdmpContextsBackupByIDReader is a Reader for the GetNdmpContextsBackupByID structure.
type GetNdmpContextsBackupByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetNdmpContextsBackupByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetNdmpContextsBackupByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetNdmpContextsBackupByIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetNdmpContextsBackupByIDOK creates a GetNdmpContextsBackupByIDOK with default headers values
func NewGetNdmpContextsBackupByIDOK() *GetNdmpContextsBackupByIDOK {
	return &GetNdmpContextsBackupByIDOK{}
}

/*GetNdmpContextsBackupByIDOK handles this case with default header values.

View a NDMP backup context
*/
type GetNdmpContextsBackupByIDOK struct {
	Payload *models.NdmpContextsBackup
}

func (o *GetNdmpContextsBackupByIDOK) Error() string {
	return fmt.Sprintf("[GET /platform/3/protocols/ndmp/contexts/backup/{NdmpContextsBackupId}][%d] getNdmpContextsBackupByIdOK  %+v", 200, o.Payload)
}

func (o *GetNdmpContextsBackupByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.NdmpContextsBackup)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetNdmpContextsBackupByIDDefault creates a GetNdmpContextsBackupByIDDefault with default headers values
func NewGetNdmpContextsBackupByIDDefault(code int) *GetNdmpContextsBackupByIDDefault {
	return &GetNdmpContextsBackupByIDDefault{
		_statusCode: code,
	}
}

/*GetNdmpContextsBackupByIDDefault handles this case with default header values.

Unexpected error
*/
type GetNdmpContextsBackupByIDDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get ndmp contexts backup by Id default response
func (o *GetNdmpContextsBackupByIDDefault) Code() int {
	return o._statusCode
}

func (o *GetNdmpContextsBackupByIDDefault) Error() string {
	return fmt.Sprintf("[GET /platform/3/protocols/ndmp/contexts/backup/{NdmpContextsBackupId}][%d] getNdmpContextsBackupById default  %+v", o._statusCode, o.Payload)
}

func (o *GetNdmpContextsBackupByIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
