// Code generated by go-swagger; DO NOT EDIT.

package protocols

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/tenortim/isi_sdk_go/models"
)

// GetSmbShareReader is a Reader for the GetSmbShare structure.
type GetSmbShareReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSmbShareReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetSmbShareOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetSmbShareDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetSmbShareOK creates a GetSmbShareOK with default headers values
func NewGetSmbShareOK() *GetSmbShareOK {
	return &GetSmbShareOK{}
}

/*GetSmbShareOK handles this case with default header values.

Retrieve share.
*/
type GetSmbShareOK struct {
	Payload *models.SmbShares
}

func (o *GetSmbShareOK) Error() string {
	return fmt.Sprintf("[GET /platform/3/protocols/smb/shares/{SmbShareId}][%d] getSmbShareOK  %+v", 200, o.Payload)
}

func (o *GetSmbShareOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SmbShares)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSmbShareDefault creates a GetSmbShareDefault with default headers values
func NewGetSmbShareDefault(code int) *GetSmbShareDefault {
	return &GetSmbShareDefault{
		_statusCode: code,
	}
}

/*GetSmbShareDefault handles this case with default header values.

Unexpected error
*/
type GetSmbShareDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get smb share default response
func (o *GetSmbShareDefault) Code() int {
	return o._statusCode
}

func (o *GetSmbShareDefault) Error() string {
	return fmt.Sprintf("[GET /platform/3/protocols/smb/shares/{SmbShareId}][%d] getSmbShare default  %+v", o._statusCode, o.Payload)
}

func (o *GetSmbShareDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
