// Code generated by go-swagger; DO NOT EDIT.

package protocols

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetNdmpSettingsDmasParams creates a new GetNdmpSettingsDmasParams object
// with the default values initialized.
func NewGetNdmpSettingsDmasParams() *GetNdmpSettingsDmasParams {

	return &GetNdmpSettingsDmasParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetNdmpSettingsDmasParamsWithTimeout creates a new GetNdmpSettingsDmasParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetNdmpSettingsDmasParamsWithTimeout(timeout time.Duration) *GetNdmpSettingsDmasParams {

	return &GetNdmpSettingsDmasParams{

		timeout: timeout,
	}
}

// NewGetNdmpSettingsDmasParamsWithContext creates a new GetNdmpSettingsDmasParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetNdmpSettingsDmasParamsWithContext(ctx context.Context) *GetNdmpSettingsDmasParams {

	return &GetNdmpSettingsDmasParams{

		Context: ctx,
	}
}

// NewGetNdmpSettingsDmasParamsWithHTTPClient creates a new GetNdmpSettingsDmasParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetNdmpSettingsDmasParamsWithHTTPClient(client *http.Client) *GetNdmpSettingsDmasParams {

	return &GetNdmpSettingsDmasParams{
		HTTPClient: client,
	}
}

/*GetNdmpSettingsDmasParams contains all the parameters to send to the API endpoint
for the get ndmp settings dmas operation typically these are written to a http.Request
*/
type GetNdmpSettingsDmasParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get ndmp settings dmas params
func (o *GetNdmpSettingsDmasParams) WithTimeout(timeout time.Duration) *GetNdmpSettingsDmasParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get ndmp settings dmas params
func (o *GetNdmpSettingsDmasParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get ndmp settings dmas params
func (o *GetNdmpSettingsDmasParams) WithContext(ctx context.Context) *GetNdmpSettingsDmasParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get ndmp settings dmas params
func (o *GetNdmpSettingsDmasParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get ndmp settings dmas params
func (o *GetNdmpSettingsDmasParams) WithHTTPClient(client *http.Client) *GetNdmpSettingsDmasParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get ndmp settings dmas params
func (o *GetNdmpSettingsDmasParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetNdmpSettingsDmasParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
