// Code generated by go-swagger; DO NOT EDIT.

package protocols

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetHTTPSettingsParams creates a new GetHTTPSettingsParams object
// with the default values initialized.
func NewGetHTTPSettingsParams() *GetHTTPSettingsParams {

	return &GetHTTPSettingsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetHTTPSettingsParamsWithTimeout creates a new GetHTTPSettingsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetHTTPSettingsParamsWithTimeout(timeout time.Duration) *GetHTTPSettingsParams {

	return &GetHTTPSettingsParams{

		timeout: timeout,
	}
}

// NewGetHTTPSettingsParamsWithContext creates a new GetHTTPSettingsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetHTTPSettingsParamsWithContext(ctx context.Context) *GetHTTPSettingsParams {

	return &GetHTTPSettingsParams{

		Context: ctx,
	}
}

// NewGetHTTPSettingsParamsWithHTTPClient creates a new GetHTTPSettingsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetHTTPSettingsParamsWithHTTPClient(client *http.Client) *GetHTTPSettingsParams {

	return &GetHTTPSettingsParams{
		HTTPClient: client,
	}
}

/*GetHTTPSettingsParams contains all the parameters to send to the API endpoint
for the get Http settings operation typically these are written to a http.Request
*/
type GetHTTPSettingsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get Http settings params
func (o *GetHTTPSettingsParams) WithTimeout(timeout time.Duration) *GetHTTPSettingsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get Http settings params
func (o *GetHTTPSettingsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get Http settings params
func (o *GetHTTPSettingsParams) WithContext(ctx context.Context) *GetHTTPSettingsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get Http settings params
func (o *GetHTTPSettingsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get Http settings params
func (o *GetHTTPSettingsParams) WithHTTPClient(client *http.Client) *GetHTTPSettingsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get Http settings params
func (o *GetHTTPSettingsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetHTTPSettingsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
