// Code generated by go-swagger; DO NOT EDIT.

package protocols

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/tenortim/isi_sdk_go/models"
)

// GetSwiftAccountReader is a Reader for the GetSwiftAccount structure.
type GetSwiftAccountReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSwiftAccountReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetSwiftAccountOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetSwiftAccountDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetSwiftAccountOK creates a GetSwiftAccountOK with default headers values
func NewGetSwiftAccountOK() *GetSwiftAccountOK {
	return &GetSwiftAccountOK{}
}

/*GetSwiftAccountOK handles this case with default header values.

List a swift account.
*/
type GetSwiftAccountOK struct {
	Payload *models.SwiftAccounts
}

func (o *GetSwiftAccountOK) Error() string {
	return fmt.Sprintf("[GET /platform/3/protocols/swift/accounts/{SwiftAccountId}][%d] getSwiftAccountOK  %+v", 200, o.Payload)
}

func (o *GetSwiftAccountOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SwiftAccounts)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSwiftAccountDefault creates a GetSwiftAccountDefault with default headers values
func NewGetSwiftAccountDefault(code int) *GetSwiftAccountDefault {
	return &GetSwiftAccountDefault{
		_statusCode: code,
	}
}

/*GetSwiftAccountDefault handles this case with default header values.

Unexpected error
*/
type GetSwiftAccountDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get swift account default response
func (o *GetSwiftAccountDefault) Code() int {
	return o._statusCode
}

func (o *GetSwiftAccountDefault) Error() string {
	return fmt.Sprintf("[GET /platform/3/protocols/swift/accounts/{SwiftAccountId}][%d] getSwiftAccount default  %+v", o._statusCode, o.Payload)
}

func (o *GetSwiftAccountDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
