// Code generated by go-swagger; DO NOT EDIT.

package protocols

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/tenortim/isi_sdk_go/models"
)

// GetNdmpUserReader is a Reader for the GetNdmpUser structure.
type GetNdmpUserReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetNdmpUserReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetNdmpUserOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetNdmpUserDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetNdmpUserOK creates a GetNdmpUserOK with default headers values
func NewGetNdmpUserOK() *GetNdmpUserOK {
	return &GetNdmpUserOK{}
}

/*GetNdmpUserOK handles this case with default header values.

Retrieve the user.
*/
type GetNdmpUserOK struct {
	Payload *models.NdmpUsers
}

func (o *GetNdmpUserOK) Error() string {
	return fmt.Sprintf("[GET /platform/3/protocols/ndmp/users/{NdmpUserId}][%d] getNdmpUserOK  %+v", 200, o.Payload)
}

func (o *GetNdmpUserOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.NdmpUsers)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetNdmpUserDefault creates a GetNdmpUserDefault with default headers values
func NewGetNdmpUserDefault(code int) *GetNdmpUserDefault {
	return &GetNdmpUserDefault{
		_statusCode: code,
	}
}

/*GetNdmpUserDefault handles this case with default header values.

Unexpected error
*/
type GetNdmpUserDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get ndmp user default response
func (o *GetNdmpUserDefault) Code() int {
	return o._statusCode
}

func (o *GetNdmpUserDefault) Error() string {
	return fmt.Sprintf("[GET /platform/3/protocols/ndmp/users/{NdmpUserId}][%d] getNdmpUser default  %+v", o._statusCode, o.Payload)
}

func (o *GetNdmpUserDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
