// Code generated by go-swagger; DO NOT EDIT.

package protocols

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/tenortim/isi_sdk_go/models"
)

// NewUpdateNfsAliasParams creates a new UpdateNfsAliasParams object
// with the default values initialized.
func NewUpdateNfsAliasParams() *UpdateNfsAliasParams {
	var ()
	return &UpdateNfsAliasParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateNfsAliasParamsWithTimeout creates a new UpdateNfsAliasParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateNfsAliasParamsWithTimeout(timeout time.Duration) *UpdateNfsAliasParams {
	var ()
	return &UpdateNfsAliasParams{

		timeout: timeout,
	}
}

// NewUpdateNfsAliasParamsWithContext creates a new UpdateNfsAliasParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateNfsAliasParamsWithContext(ctx context.Context) *UpdateNfsAliasParams {
	var ()
	return &UpdateNfsAliasParams{

		Context: ctx,
	}
}

// NewUpdateNfsAliasParamsWithHTTPClient creates a new UpdateNfsAliasParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateNfsAliasParamsWithHTTPClient(client *http.Client) *UpdateNfsAliasParams {
	var ()
	return &UpdateNfsAliasParams{
		HTTPClient: client,
	}
}

/*UpdateNfsAliasParams contains all the parameters to send to the API endpoint
for the update nfs alias operation typically these are written to a http.Request
*/
type UpdateNfsAliasParams struct {

	/*NfsAlias*/
	NfsAlias *models.NfsAlias
	/*NfsAliasID
	  Modify the alias. All input fields are optional, but one or more must be supplied.

	*/
	NfsAliasID string
	/*Zone
	  Access zone

	*/
	Zone *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update nfs alias params
func (o *UpdateNfsAliasParams) WithTimeout(timeout time.Duration) *UpdateNfsAliasParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update nfs alias params
func (o *UpdateNfsAliasParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update nfs alias params
func (o *UpdateNfsAliasParams) WithContext(ctx context.Context) *UpdateNfsAliasParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update nfs alias params
func (o *UpdateNfsAliasParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update nfs alias params
func (o *UpdateNfsAliasParams) WithHTTPClient(client *http.Client) *UpdateNfsAliasParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update nfs alias params
func (o *UpdateNfsAliasParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithNfsAlias adds the nfsAlias to the update nfs alias params
func (o *UpdateNfsAliasParams) WithNfsAlias(nfsAlias *models.NfsAlias) *UpdateNfsAliasParams {
	o.SetNfsAlias(nfsAlias)
	return o
}

// SetNfsAlias adds the nfsAlias to the update nfs alias params
func (o *UpdateNfsAliasParams) SetNfsAlias(nfsAlias *models.NfsAlias) {
	o.NfsAlias = nfsAlias
}

// WithNfsAliasID adds the nfsAliasID to the update nfs alias params
func (o *UpdateNfsAliasParams) WithNfsAliasID(nfsAliasID string) *UpdateNfsAliasParams {
	o.SetNfsAliasID(nfsAliasID)
	return o
}

// SetNfsAliasID adds the nfsAliasId to the update nfs alias params
func (o *UpdateNfsAliasParams) SetNfsAliasID(nfsAliasID string) {
	o.NfsAliasID = nfsAliasID
}

// WithZone adds the zone to the update nfs alias params
func (o *UpdateNfsAliasParams) WithZone(zone *string) *UpdateNfsAliasParams {
	o.SetZone(zone)
	return o
}

// SetZone adds the zone to the update nfs alias params
func (o *UpdateNfsAliasParams) SetZone(zone *string) {
	o.Zone = zone
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateNfsAliasParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.NfsAlias != nil {
		if err := r.SetBodyParam(o.NfsAlias); err != nil {
			return err
		}
	}

	// path param NfsAliasId
	if err := r.SetPathParam("NfsAliasId", o.NfsAliasID); err != nil {
		return err
	}

	if o.Zone != nil {

		// query param zone
		var qrZone string
		if o.Zone != nil {
			qrZone = *o.Zone
		}
		qZone := qrZone
		if qZone != "" {
			if err := r.SetQueryParam("zone", qZone); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
