// Code generated by go-swagger; DO NOT EDIT.

package protocols

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/tenortim/isi_sdk_go/models"
)

// NewUpdateNfsExportParams creates a new UpdateNfsExportParams object
// with the default values initialized.
func NewUpdateNfsExportParams() *UpdateNfsExportParams {
	var ()
	return &UpdateNfsExportParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateNfsExportParamsWithTimeout creates a new UpdateNfsExportParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateNfsExportParamsWithTimeout(timeout time.Duration) *UpdateNfsExportParams {
	var ()
	return &UpdateNfsExportParams{

		timeout: timeout,
	}
}

// NewUpdateNfsExportParamsWithContext creates a new UpdateNfsExportParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateNfsExportParamsWithContext(ctx context.Context) *UpdateNfsExportParams {
	var ()
	return &UpdateNfsExportParams{

		Context: ctx,
	}
}

// NewUpdateNfsExportParamsWithHTTPClient creates a new UpdateNfsExportParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateNfsExportParamsWithHTTPClient(client *http.Client) *UpdateNfsExportParams {
	var ()
	return &UpdateNfsExportParams{
		HTTPClient: client,
	}
}

/*UpdateNfsExportParams contains all the parameters to send to the API endpoint
for the update nfs export operation typically these are written to a http.Request
*/
type UpdateNfsExportParams struct {

	/*NfsExport*/
	NfsExport *models.NfsExport
	/*NfsExportID
	  Modify the export. All input fields are optional, but one or more must be supplied.

	*/
	NfsExportID string
	/*Force
	  If true, the export will be updated even if that change conflicts with another export.

	*/
	Force *bool
	/*IgnoreBadAuth
	  Ignore invalid users.

	*/
	IgnoreBadAuth *bool
	/*IgnoreBadPaths
	  Ignore nonexistent or otherwise bad paths.

	*/
	IgnoreBadPaths *bool
	/*IgnoreConflicts
	  Ignore conflicts with existing exports.

	*/
	IgnoreConflicts *bool
	/*IgnoreUnresolvableHosts
	  Ignore unresolvable hosts.

	*/
	IgnoreUnresolvableHosts *bool
	/*Zone
	  Access zone

	*/
	Zone *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update nfs export params
func (o *UpdateNfsExportParams) WithTimeout(timeout time.Duration) *UpdateNfsExportParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update nfs export params
func (o *UpdateNfsExportParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update nfs export params
func (o *UpdateNfsExportParams) WithContext(ctx context.Context) *UpdateNfsExportParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update nfs export params
func (o *UpdateNfsExportParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update nfs export params
func (o *UpdateNfsExportParams) WithHTTPClient(client *http.Client) *UpdateNfsExportParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update nfs export params
func (o *UpdateNfsExportParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithNfsExport adds the nfsExport to the update nfs export params
func (o *UpdateNfsExportParams) WithNfsExport(nfsExport *models.NfsExport) *UpdateNfsExportParams {
	o.SetNfsExport(nfsExport)
	return o
}

// SetNfsExport adds the nfsExport to the update nfs export params
func (o *UpdateNfsExportParams) SetNfsExport(nfsExport *models.NfsExport) {
	o.NfsExport = nfsExport
}

// WithNfsExportID adds the nfsExportID to the update nfs export params
func (o *UpdateNfsExportParams) WithNfsExportID(nfsExportID string) *UpdateNfsExportParams {
	o.SetNfsExportID(nfsExportID)
	return o
}

// SetNfsExportID adds the nfsExportId to the update nfs export params
func (o *UpdateNfsExportParams) SetNfsExportID(nfsExportID string) {
	o.NfsExportID = nfsExportID
}

// WithForce adds the force to the update nfs export params
func (o *UpdateNfsExportParams) WithForce(force *bool) *UpdateNfsExportParams {
	o.SetForce(force)
	return o
}

// SetForce adds the force to the update nfs export params
func (o *UpdateNfsExportParams) SetForce(force *bool) {
	o.Force = force
}

// WithIgnoreBadAuth adds the ignoreBadAuth to the update nfs export params
func (o *UpdateNfsExportParams) WithIgnoreBadAuth(ignoreBadAuth *bool) *UpdateNfsExportParams {
	o.SetIgnoreBadAuth(ignoreBadAuth)
	return o
}

// SetIgnoreBadAuth adds the ignoreBadAuth to the update nfs export params
func (o *UpdateNfsExportParams) SetIgnoreBadAuth(ignoreBadAuth *bool) {
	o.IgnoreBadAuth = ignoreBadAuth
}

// WithIgnoreBadPaths adds the ignoreBadPaths to the update nfs export params
func (o *UpdateNfsExportParams) WithIgnoreBadPaths(ignoreBadPaths *bool) *UpdateNfsExportParams {
	o.SetIgnoreBadPaths(ignoreBadPaths)
	return o
}

// SetIgnoreBadPaths adds the ignoreBadPaths to the update nfs export params
func (o *UpdateNfsExportParams) SetIgnoreBadPaths(ignoreBadPaths *bool) {
	o.IgnoreBadPaths = ignoreBadPaths
}

// WithIgnoreConflicts adds the ignoreConflicts to the update nfs export params
func (o *UpdateNfsExportParams) WithIgnoreConflicts(ignoreConflicts *bool) *UpdateNfsExportParams {
	o.SetIgnoreConflicts(ignoreConflicts)
	return o
}

// SetIgnoreConflicts adds the ignoreConflicts to the update nfs export params
func (o *UpdateNfsExportParams) SetIgnoreConflicts(ignoreConflicts *bool) {
	o.IgnoreConflicts = ignoreConflicts
}

// WithIgnoreUnresolvableHosts adds the ignoreUnresolvableHosts to the update nfs export params
func (o *UpdateNfsExportParams) WithIgnoreUnresolvableHosts(ignoreUnresolvableHosts *bool) *UpdateNfsExportParams {
	o.SetIgnoreUnresolvableHosts(ignoreUnresolvableHosts)
	return o
}

// SetIgnoreUnresolvableHosts adds the ignoreUnresolvableHosts to the update nfs export params
func (o *UpdateNfsExportParams) SetIgnoreUnresolvableHosts(ignoreUnresolvableHosts *bool) {
	o.IgnoreUnresolvableHosts = ignoreUnresolvableHosts
}

// WithZone adds the zone to the update nfs export params
func (o *UpdateNfsExportParams) WithZone(zone *string) *UpdateNfsExportParams {
	o.SetZone(zone)
	return o
}

// SetZone adds the zone to the update nfs export params
func (o *UpdateNfsExportParams) SetZone(zone *string) {
	o.Zone = zone
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateNfsExportParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.NfsExport != nil {
		if err := r.SetBodyParam(o.NfsExport); err != nil {
			return err
		}
	}

	// path param NfsExportId
	if err := r.SetPathParam("NfsExportId", o.NfsExportID); err != nil {
		return err
	}

	if o.Force != nil {

		// query param force
		var qrForce bool
		if o.Force != nil {
			qrForce = *o.Force
		}
		qForce := swag.FormatBool(qrForce)
		if qForce != "" {
			if err := r.SetQueryParam("force", qForce); err != nil {
				return err
			}
		}

	}

	if o.IgnoreBadAuth != nil {

		// query param ignore_bad_auth
		var qrIgnoreBadAuth bool
		if o.IgnoreBadAuth != nil {
			qrIgnoreBadAuth = *o.IgnoreBadAuth
		}
		qIgnoreBadAuth := swag.FormatBool(qrIgnoreBadAuth)
		if qIgnoreBadAuth != "" {
			if err := r.SetQueryParam("ignore_bad_auth", qIgnoreBadAuth); err != nil {
				return err
			}
		}

	}

	if o.IgnoreBadPaths != nil {

		// query param ignore_bad_paths
		var qrIgnoreBadPaths bool
		if o.IgnoreBadPaths != nil {
			qrIgnoreBadPaths = *o.IgnoreBadPaths
		}
		qIgnoreBadPaths := swag.FormatBool(qrIgnoreBadPaths)
		if qIgnoreBadPaths != "" {
			if err := r.SetQueryParam("ignore_bad_paths", qIgnoreBadPaths); err != nil {
				return err
			}
		}

	}

	if o.IgnoreConflicts != nil {

		// query param ignore_conflicts
		var qrIgnoreConflicts bool
		if o.IgnoreConflicts != nil {
			qrIgnoreConflicts = *o.IgnoreConflicts
		}
		qIgnoreConflicts := swag.FormatBool(qrIgnoreConflicts)
		if qIgnoreConflicts != "" {
			if err := r.SetQueryParam("ignore_conflicts", qIgnoreConflicts); err != nil {
				return err
			}
		}

	}

	if o.IgnoreUnresolvableHosts != nil {

		// query param ignore_unresolvable_hosts
		var qrIgnoreUnresolvableHosts bool
		if o.IgnoreUnresolvableHosts != nil {
			qrIgnoreUnresolvableHosts = *o.IgnoreUnresolvableHosts
		}
		qIgnoreUnresolvableHosts := swag.FormatBool(qrIgnoreUnresolvableHosts)
		if qIgnoreUnresolvableHosts != "" {
			if err := r.SetQueryParam("ignore_unresolvable_hosts", qIgnoreUnresolvableHosts); err != nil {
				return err
			}
		}

	}

	if o.Zone != nil {

		// query param zone
		var qrZone string
		if o.Zone != nil {
			qrZone = *o.Zone
		}
		qZone := qrZone
		if qZone != "" {
			if err := r.SetQueryParam("zone", qZone); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
