// Code generated by go-swagger; DO NOT EDIT.

package protocols

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/tenortim/isi_sdk_go/models"
)

// NewUpdateSmbShareParams creates a new UpdateSmbShareParams object
// with the default values initialized.
func NewUpdateSmbShareParams() *UpdateSmbShareParams {
	var ()
	return &UpdateSmbShareParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateSmbShareParamsWithTimeout creates a new UpdateSmbShareParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateSmbShareParamsWithTimeout(timeout time.Duration) *UpdateSmbShareParams {
	var ()
	return &UpdateSmbShareParams{

		timeout: timeout,
	}
}

// NewUpdateSmbShareParamsWithContext creates a new UpdateSmbShareParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateSmbShareParamsWithContext(ctx context.Context) *UpdateSmbShareParams {
	var ()
	return &UpdateSmbShareParams{

		Context: ctx,
	}
}

// NewUpdateSmbShareParamsWithHTTPClient creates a new UpdateSmbShareParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateSmbShareParamsWithHTTPClient(client *http.Client) *UpdateSmbShareParams {
	var ()
	return &UpdateSmbShareParams{
		HTTPClient: client,
	}
}

/*UpdateSmbShareParams contains all the parameters to send to the API endpoint
for the update smb share operation typically these are written to a http.Request
*/
type UpdateSmbShareParams struct {

	/*SmbShare*/
	SmbShare *models.SmbShare
	/*SmbShareID
	  Modify share. All input fields are optional, but one or more must be supplied.

	*/
	SmbShareID string
	/*Zone
	  Zone which contains this share.

	*/
	Zone *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update smb share params
func (o *UpdateSmbShareParams) WithTimeout(timeout time.Duration) *UpdateSmbShareParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update smb share params
func (o *UpdateSmbShareParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update smb share params
func (o *UpdateSmbShareParams) WithContext(ctx context.Context) *UpdateSmbShareParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update smb share params
func (o *UpdateSmbShareParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update smb share params
func (o *UpdateSmbShareParams) WithHTTPClient(client *http.Client) *UpdateSmbShareParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update smb share params
func (o *UpdateSmbShareParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSmbShare adds the smbShare to the update smb share params
func (o *UpdateSmbShareParams) WithSmbShare(smbShare *models.SmbShare) *UpdateSmbShareParams {
	o.SetSmbShare(smbShare)
	return o
}

// SetSmbShare adds the smbShare to the update smb share params
func (o *UpdateSmbShareParams) SetSmbShare(smbShare *models.SmbShare) {
	o.SmbShare = smbShare
}

// WithSmbShareID adds the smbShareID to the update smb share params
func (o *UpdateSmbShareParams) WithSmbShareID(smbShareID string) *UpdateSmbShareParams {
	o.SetSmbShareID(smbShareID)
	return o
}

// SetSmbShareID adds the smbShareId to the update smb share params
func (o *UpdateSmbShareParams) SetSmbShareID(smbShareID string) {
	o.SmbShareID = smbShareID
}

// WithZone adds the zone to the update smb share params
func (o *UpdateSmbShareParams) WithZone(zone *string) *UpdateSmbShareParams {
	o.SetZone(zone)
	return o
}

// SetZone adds the zone to the update smb share params
func (o *UpdateSmbShareParams) SetZone(zone *string) {
	o.Zone = zone
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateSmbShareParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.SmbShare != nil {
		if err := r.SetBodyParam(o.SmbShare); err != nil {
			return err
		}
	}

	// path param SmbShareId
	if err := r.SetPathParam("SmbShareId", o.SmbShareID); err != nil {
		return err
	}

	if o.Zone != nil {

		// query param zone
		var qrZone string
		if o.Zone != nil {
			qrZone = *o.Zone
		}
		qZone := qrZone
		if qZone != "" {
			if err := r.SetQueryParam("zone", qZone); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
