// Code generated by go-swagger; DO NOT EDIT.

package protocols

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/tenortim/isi_sdk_go/models"
)

// UpdateNfsAliasReader is a Reader for the UpdateNfsAlias structure.
type UpdateNfsAliasReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateNfsAliasReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewUpdateNfsAliasNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewUpdateNfsAliasDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewUpdateNfsAliasNoContent creates a UpdateNfsAliasNoContent with default headers values
func NewUpdateNfsAliasNoContent() *UpdateNfsAliasNoContent {
	return &UpdateNfsAliasNoContent{}
}

/*UpdateNfsAliasNoContent handles this case with default header values.

Success.
*/
type UpdateNfsAliasNoContent struct {
}

func (o *UpdateNfsAliasNoContent) Error() string {
	return fmt.Sprintf("[PUT /platform/2/protocols/nfs/aliases/{NfsAliasId}][%d] updateNfsAliasNoContent ", 204)
}

func (o *UpdateNfsAliasNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateNfsAliasDefault creates a UpdateNfsAliasDefault with default headers values
func NewUpdateNfsAliasDefault(code int) *UpdateNfsAliasDefault {
	return &UpdateNfsAliasDefault{
		_statusCode: code,
	}
}

/*UpdateNfsAliasDefault handles this case with default header values.

Unexpected error
*/
type UpdateNfsAliasDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the update nfs alias default response
func (o *UpdateNfsAliasDefault) Code() int {
	return o._statusCode
}

func (o *UpdateNfsAliasDefault) Error() string {
	return fmt.Sprintf("[PUT /platform/2/protocols/nfs/aliases/{NfsAliasId}][%d] updateNfsAlias default  %+v", o._statusCode, o.Payload)
}

func (o *UpdateNfsAliasDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
