// Code generated by go-swagger; DO NOT EDIT.

package storagepool

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/tenortim/isi_sdk_go/models"
)

// DeleteStoragepoolTiersReader is a Reader for the DeleteStoragepoolTiers structure.
type DeleteStoragepoolTiersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteStoragepoolTiersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDeleteStoragepoolTiersNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewDeleteStoragepoolTiersDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteStoragepoolTiersNoContent creates a DeleteStoragepoolTiersNoContent with default headers values
func NewDeleteStoragepoolTiersNoContent() *DeleteStoragepoolTiersNoContent {
	return &DeleteStoragepoolTiersNoContent{}
}

/*DeleteStoragepoolTiersNoContent handles this case with default header values.

Success.
*/
type DeleteStoragepoolTiersNoContent struct {
}

func (o *DeleteStoragepoolTiersNoContent) Error() string {
	return fmt.Sprintf("[DELETE /platform/1/storagepool/tiers][%d] deleteStoragepoolTiersNoContent ", 204)
}

func (o *DeleteStoragepoolTiersNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteStoragepoolTiersDefault creates a DeleteStoragepoolTiersDefault with default headers values
func NewDeleteStoragepoolTiersDefault(code int) *DeleteStoragepoolTiersDefault {
	return &DeleteStoragepoolTiersDefault{
		_statusCode: code,
	}
}

/*DeleteStoragepoolTiersDefault handles this case with default header values.

Unexpected error
*/
type DeleteStoragepoolTiersDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the delete storagepool tiers default response
func (o *DeleteStoragepoolTiersDefault) Code() int {
	return o._statusCode
}

func (o *DeleteStoragepoolTiersDefault) Error() string {
	return fmt.Sprintf("[DELETE /platform/1/storagepool/tiers][%d] deleteStoragepoolTiers default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteStoragepoolTiersDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
