// Code generated by go-swagger; DO NOT EDIT.

package storagepool

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetCompatibilitiesClassActiveByIDParams creates a new GetCompatibilitiesClassActiveByIDParams object
// with the default values initialized.
func NewGetCompatibilitiesClassActiveByIDParams() *GetCompatibilitiesClassActiveByIDParams {
	var ()
	return &GetCompatibilitiesClassActiveByIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetCompatibilitiesClassActiveByIDParamsWithTimeout creates a new GetCompatibilitiesClassActiveByIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetCompatibilitiesClassActiveByIDParamsWithTimeout(timeout time.Duration) *GetCompatibilitiesClassActiveByIDParams {
	var ()
	return &GetCompatibilitiesClassActiveByIDParams{

		timeout: timeout,
	}
}

// NewGetCompatibilitiesClassActiveByIDParamsWithContext creates a new GetCompatibilitiesClassActiveByIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetCompatibilitiesClassActiveByIDParamsWithContext(ctx context.Context) *GetCompatibilitiesClassActiveByIDParams {
	var ()
	return &GetCompatibilitiesClassActiveByIDParams{

		Context: ctx,
	}
}

// NewGetCompatibilitiesClassActiveByIDParamsWithHTTPClient creates a new GetCompatibilitiesClassActiveByIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetCompatibilitiesClassActiveByIDParamsWithHTTPClient(client *http.Client) *GetCompatibilitiesClassActiveByIDParams {
	var ()
	return &GetCompatibilitiesClassActiveByIDParams{
		HTTPClient: client,
	}
}

/*GetCompatibilitiesClassActiveByIDParams contains all the parameters to send to the API endpoint
for the get compatibilities class active by Id operation typically these are written to a http.Request
*/
type GetCompatibilitiesClassActiveByIDParams struct {

	/*CompatibilitiesClassActiveID
	  Get an active compatibilities by id

	*/
	CompatibilitiesClassActiveID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get compatibilities class active by Id params
func (o *GetCompatibilitiesClassActiveByIDParams) WithTimeout(timeout time.Duration) *GetCompatibilitiesClassActiveByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get compatibilities class active by Id params
func (o *GetCompatibilitiesClassActiveByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get compatibilities class active by Id params
func (o *GetCompatibilitiesClassActiveByIDParams) WithContext(ctx context.Context) *GetCompatibilitiesClassActiveByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get compatibilities class active by Id params
func (o *GetCompatibilitiesClassActiveByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get compatibilities class active by Id params
func (o *GetCompatibilitiesClassActiveByIDParams) WithHTTPClient(client *http.Client) *GetCompatibilitiesClassActiveByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get compatibilities class active by Id params
func (o *GetCompatibilitiesClassActiveByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCompatibilitiesClassActiveID adds the compatibilitiesClassActiveID to the get compatibilities class active by Id params
func (o *GetCompatibilitiesClassActiveByIDParams) WithCompatibilitiesClassActiveID(compatibilitiesClassActiveID string) *GetCompatibilitiesClassActiveByIDParams {
	o.SetCompatibilitiesClassActiveID(compatibilitiesClassActiveID)
	return o
}

// SetCompatibilitiesClassActiveID adds the compatibilitiesClassActiveId to the get compatibilities class active by Id params
func (o *GetCompatibilitiesClassActiveByIDParams) SetCompatibilitiesClassActiveID(compatibilitiesClassActiveID string) {
	o.CompatibilitiesClassActiveID = compatibilitiesClassActiveID
}

// WriteToRequest writes these params to a swagger request
func (o *GetCompatibilitiesClassActiveByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param CompatibilitiesClassActiveId
	if err := r.SetPathParam("CompatibilitiesClassActiveId", o.CompatibilitiesClassActiveID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
