// Code generated by go-swagger; DO NOT EDIT.

package storagepool

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetCompatibilitiesSsdAvailableParams creates a new GetCompatibilitiesSsdAvailableParams object
// with the default values initialized.
func NewGetCompatibilitiesSsdAvailableParams() *GetCompatibilitiesSsdAvailableParams {

	return &GetCompatibilitiesSsdAvailableParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetCompatibilitiesSsdAvailableParamsWithTimeout creates a new GetCompatibilitiesSsdAvailableParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetCompatibilitiesSsdAvailableParamsWithTimeout(timeout time.Duration) *GetCompatibilitiesSsdAvailableParams {

	return &GetCompatibilitiesSsdAvailableParams{

		timeout: timeout,
	}
}

// NewGetCompatibilitiesSsdAvailableParamsWithContext creates a new GetCompatibilitiesSsdAvailableParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetCompatibilitiesSsdAvailableParamsWithContext(ctx context.Context) *GetCompatibilitiesSsdAvailableParams {

	return &GetCompatibilitiesSsdAvailableParams{

		Context: ctx,
	}
}

// NewGetCompatibilitiesSsdAvailableParamsWithHTTPClient creates a new GetCompatibilitiesSsdAvailableParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetCompatibilitiesSsdAvailableParamsWithHTTPClient(client *http.Client) *GetCompatibilitiesSsdAvailableParams {

	return &GetCompatibilitiesSsdAvailableParams{
		HTTPClient: client,
	}
}

/*GetCompatibilitiesSsdAvailableParams contains all the parameters to send to the API endpoint
for the get compatibilities ssd available operation typically these are written to a http.Request
*/
type GetCompatibilitiesSsdAvailableParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get compatibilities ssd available params
func (o *GetCompatibilitiesSsdAvailableParams) WithTimeout(timeout time.Duration) *GetCompatibilitiesSsdAvailableParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get compatibilities ssd available params
func (o *GetCompatibilitiesSsdAvailableParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get compatibilities ssd available params
func (o *GetCompatibilitiesSsdAvailableParams) WithContext(ctx context.Context) *GetCompatibilitiesSsdAvailableParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get compatibilities ssd available params
func (o *GetCompatibilitiesSsdAvailableParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get compatibilities ssd available params
func (o *GetCompatibilitiesSsdAvailableParams) WithHTTPClient(client *http.Client) *GetCompatibilitiesSsdAvailableParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get compatibilities ssd available params
func (o *GetCompatibilitiesSsdAvailableParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetCompatibilitiesSsdAvailableParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
