// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/tenortim/isi_sdk_go/models"
)

// CreateSettingsKrb5RealmReader is a Reader for the CreateSettingsKrb5Realm structure.
type CreateSettingsKrb5RealmReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateSettingsKrb5RealmReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCreateSettingsKrb5RealmOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewCreateSettingsKrb5RealmDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCreateSettingsKrb5RealmOK creates a CreateSettingsKrb5RealmOK with default headers values
func NewCreateSettingsKrb5RealmOK() *CreateSettingsKrb5RealmOK {
	return &CreateSettingsKrb5RealmOK{}
}

/*CreateSettingsKrb5RealmOK handles this case with default header values.

Create a new krb5 realm.
*/
type CreateSettingsKrb5RealmOK struct {
	Payload *models.CreateResponse
}

func (o *CreateSettingsKrb5RealmOK) Error() string {
	return fmt.Sprintf("[POST /platform/1/auth/settings/krb5/realms][%d] createSettingsKrb5RealmOK  %+v", 200, o.Payload)
}

func (o *CreateSettingsKrb5RealmOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CreateResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateSettingsKrb5RealmDefault creates a CreateSettingsKrb5RealmDefault with default headers values
func NewCreateSettingsKrb5RealmDefault(code int) *CreateSettingsKrb5RealmDefault {
	return &CreateSettingsKrb5RealmDefault{
		_statusCode: code,
	}
}

/*CreateSettingsKrb5RealmDefault handles this case with default header values.

Unexpected error
*/
type CreateSettingsKrb5RealmDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the create settings krb5 realm default response
func (o *CreateSettingsKrb5RealmDefault) Code() int {
	return o._statusCode
}

func (o *CreateSettingsKrb5RealmDefault) Error() string {
	return fmt.Sprintf("[POST /platform/1/auth/settings/krb5/realms][%d] createSettingsKrb5Realm default  %+v", o._statusCode, o.Payload)
}

func (o *CreateSettingsKrb5RealmDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
