// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/tenortim/isi_sdk_go/models"
)

// DeleteMappingIdentityReader is a Reader for the DeleteMappingIdentity structure.
type DeleteMappingIdentityReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteMappingIdentityReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDeleteMappingIdentityNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewDeleteMappingIdentityDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteMappingIdentityNoContent creates a DeleteMappingIdentityNoContent with default headers values
func NewDeleteMappingIdentityNoContent() *DeleteMappingIdentityNoContent {
	return &DeleteMappingIdentityNoContent{}
}

/*DeleteMappingIdentityNoContent handles this case with default header values.

Success.
*/
type DeleteMappingIdentityNoContent struct {
}

func (o *DeleteMappingIdentityNoContent) Error() string {
	return fmt.Sprintf("[DELETE /platform/1/auth/mapping/identities/{MappingIdentityId}][%d] deleteMappingIdentityNoContent ", 204)
}

func (o *DeleteMappingIdentityNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteMappingIdentityDefault creates a DeleteMappingIdentityDefault with default headers values
func NewDeleteMappingIdentityDefault(code int) *DeleteMappingIdentityDefault {
	return &DeleteMappingIdentityDefault{
		_statusCode: code,
	}
}

/*DeleteMappingIdentityDefault handles this case with default header values.

Unexpected error
*/
type DeleteMappingIdentityDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the delete mapping identity default response
func (o *DeleteMappingIdentityDefault) Code() int {
	return o._statusCode
}

func (o *DeleteMappingIdentityDefault) Error() string {
	return fmt.Sprintf("[DELETE /platform/1/auth/mapping/identities/{MappingIdentityId}][%d] deleteMappingIdentity default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteMappingIdentityDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
