// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/tenortim/isi_sdk_go/models"
)

// GetSettingsKrb5DefaultsReader is a Reader for the GetSettingsKrb5Defaults structure.
type GetSettingsKrb5DefaultsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSettingsKrb5DefaultsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetSettingsKrb5DefaultsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetSettingsKrb5DefaultsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetSettingsKrb5DefaultsOK creates a GetSettingsKrb5DefaultsOK with default headers values
func NewGetSettingsKrb5DefaultsOK() *GetSettingsKrb5DefaultsOK {
	return &GetSettingsKrb5DefaultsOK{}
}

/*GetSettingsKrb5DefaultsOK handles this case with default header values.

Retrieve the krb5 settings.
*/
type GetSettingsKrb5DefaultsOK struct {
	Payload *models.SettingsKrb5Defaults
}

func (o *GetSettingsKrb5DefaultsOK) Error() string {
	return fmt.Sprintf("[GET /platform/1/auth/settings/krb5/defaults][%d] getSettingsKrb5DefaultsOK  %+v", 200, o.Payload)
}

func (o *GetSettingsKrb5DefaultsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SettingsKrb5Defaults)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSettingsKrb5DefaultsDefault creates a GetSettingsKrb5DefaultsDefault with default headers values
func NewGetSettingsKrb5DefaultsDefault(code int) *GetSettingsKrb5DefaultsDefault {
	return &GetSettingsKrb5DefaultsDefault{
		_statusCode: code,
	}
}

/*GetSettingsKrb5DefaultsDefault handles this case with default header values.

Unexpected error
*/
type GetSettingsKrb5DefaultsDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get settings krb5 defaults default response
func (o *GetSettingsKrb5DefaultsDefault) Code() int {
	return o._statusCode
}

func (o *GetSettingsKrb5DefaultsDefault) Error() string {
	return fmt.Sprintf("[GET /platform/1/auth/settings/krb5/defaults][%d] getSettingsKrb5Defaults default  %+v", o._statusCode, o.Payload)
}

func (o *GetSettingsKrb5DefaultsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
