// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListAuthUsersParams creates a new ListAuthUsersParams object
// with the default values initialized.
func NewListAuthUsersParams() *ListAuthUsersParams {
	var ()
	return &ListAuthUsersParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListAuthUsersParamsWithTimeout creates a new ListAuthUsersParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListAuthUsersParamsWithTimeout(timeout time.Duration) *ListAuthUsersParams {
	var ()
	return &ListAuthUsersParams{

		timeout: timeout,
	}
}

// NewListAuthUsersParamsWithContext creates a new ListAuthUsersParams object
// with the default values initialized, and the ability to set a context for a request
func NewListAuthUsersParamsWithContext(ctx context.Context) *ListAuthUsersParams {
	var ()
	return &ListAuthUsersParams{

		Context: ctx,
	}
}

// NewListAuthUsersParamsWithHTTPClient creates a new ListAuthUsersParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListAuthUsersParamsWithHTTPClient(client *http.Client) *ListAuthUsersParams {
	var ()
	return &ListAuthUsersParams{
		HTTPClient: client,
	}
}

/*ListAuthUsersParams contains all the parameters to send to the API endpoint
for the list auth users operation typically these are written to a http.Request
*/
type ListAuthUsersParams struct {

	/*Cached
	  If true, only return cached objects.

	*/
	Cached *bool
	/*Domain
	  Filter users by domain.

	*/
	Domain *string
	/*Filter
	  Filter users by name prefix.

	*/
	Filter *string
	/*Limit
	  Return no more than this many results at once (see resume).

	*/
	Limit *int64
	/*Provider
	  Filter users by provider.

	*/
	Provider *string
	/*QueryMemberOf
	  Enumerate all users that a group is a member of.

	*/
	QueryMemberOf *bool
	/*ResolveNames
	  Resolve names of personas.

	*/
	ResolveNames *bool
	/*Resume
	  Continue returning results from previous call using this token (token should come from the previous call, resume cannot be used with other options).

	*/
	Resume *string
	/*Zone
	  Filter users by zone.

	*/
	Zone *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list auth users params
func (o *ListAuthUsersParams) WithTimeout(timeout time.Duration) *ListAuthUsersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list auth users params
func (o *ListAuthUsersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list auth users params
func (o *ListAuthUsersParams) WithContext(ctx context.Context) *ListAuthUsersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list auth users params
func (o *ListAuthUsersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list auth users params
func (o *ListAuthUsersParams) WithHTTPClient(client *http.Client) *ListAuthUsersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list auth users params
func (o *ListAuthUsersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCached adds the cached to the list auth users params
func (o *ListAuthUsersParams) WithCached(cached *bool) *ListAuthUsersParams {
	o.SetCached(cached)
	return o
}

// SetCached adds the cached to the list auth users params
func (o *ListAuthUsersParams) SetCached(cached *bool) {
	o.Cached = cached
}

// WithDomain adds the domain to the list auth users params
func (o *ListAuthUsersParams) WithDomain(domain *string) *ListAuthUsersParams {
	o.SetDomain(domain)
	return o
}

// SetDomain adds the domain to the list auth users params
func (o *ListAuthUsersParams) SetDomain(domain *string) {
	o.Domain = domain
}

// WithFilter adds the filter to the list auth users params
func (o *ListAuthUsersParams) WithFilter(filter *string) *ListAuthUsersParams {
	o.SetFilter(filter)
	return o
}

// SetFilter adds the filter to the list auth users params
func (o *ListAuthUsersParams) SetFilter(filter *string) {
	o.Filter = filter
}

// WithLimit adds the limit to the list auth users params
func (o *ListAuthUsersParams) WithLimit(limit *int64) *ListAuthUsersParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the list auth users params
func (o *ListAuthUsersParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithProvider adds the provider to the list auth users params
func (o *ListAuthUsersParams) WithProvider(provider *string) *ListAuthUsersParams {
	o.SetProvider(provider)
	return o
}

// SetProvider adds the provider to the list auth users params
func (o *ListAuthUsersParams) SetProvider(provider *string) {
	o.Provider = provider
}

// WithQueryMemberOf adds the queryMemberOf to the list auth users params
func (o *ListAuthUsersParams) WithQueryMemberOf(queryMemberOf *bool) *ListAuthUsersParams {
	o.SetQueryMemberOf(queryMemberOf)
	return o
}

// SetQueryMemberOf adds the queryMemberOf to the list auth users params
func (o *ListAuthUsersParams) SetQueryMemberOf(queryMemberOf *bool) {
	o.QueryMemberOf = queryMemberOf
}

// WithResolveNames adds the resolveNames to the list auth users params
func (o *ListAuthUsersParams) WithResolveNames(resolveNames *bool) *ListAuthUsersParams {
	o.SetResolveNames(resolveNames)
	return o
}

// SetResolveNames adds the resolveNames to the list auth users params
func (o *ListAuthUsersParams) SetResolveNames(resolveNames *bool) {
	o.ResolveNames = resolveNames
}

// WithResume adds the resume to the list auth users params
func (o *ListAuthUsersParams) WithResume(resume *string) *ListAuthUsersParams {
	o.SetResume(resume)
	return o
}

// SetResume adds the resume to the list auth users params
func (o *ListAuthUsersParams) SetResume(resume *string) {
	o.Resume = resume
}

// WithZone adds the zone to the list auth users params
func (o *ListAuthUsersParams) WithZone(zone *string) *ListAuthUsersParams {
	o.SetZone(zone)
	return o
}

// SetZone adds the zone to the list auth users params
func (o *ListAuthUsersParams) SetZone(zone *string) {
	o.Zone = zone
}

// WriteToRequest writes these params to a swagger request
func (o *ListAuthUsersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Cached != nil {

		// query param cached
		var qrCached bool
		if o.Cached != nil {
			qrCached = *o.Cached
		}
		qCached := swag.FormatBool(qrCached)
		if qCached != "" {
			if err := r.SetQueryParam("cached", qCached); err != nil {
				return err
			}
		}

	}

	if o.Domain != nil {

		// query param domain
		var qrDomain string
		if o.Domain != nil {
			qrDomain = *o.Domain
		}
		qDomain := qrDomain
		if qDomain != "" {
			if err := r.SetQueryParam("domain", qDomain); err != nil {
				return err
			}
		}

	}

	if o.Filter != nil {

		// query param filter
		var qrFilter string
		if o.Filter != nil {
			qrFilter = *o.Filter
		}
		qFilter := qrFilter
		if qFilter != "" {
			if err := r.SetQueryParam("filter", qFilter); err != nil {
				return err
			}
		}

	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {
			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	if o.Provider != nil {

		// query param provider
		var qrProvider string
		if o.Provider != nil {
			qrProvider = *o.Provider
		}
		qProvider := qrProvider
		if qProvider != "" {
			if err := r.SetQueryParam("provider", qProvider); err != nil {
				return err
			}
		}

	}

	if o.QueryMemberOf != nil {

		// query param query_member_of
		var qrQueryMemberOf bool
		if o.QueryMemberOf != nil {
			qrQueryMemberOf = *o.QueryMemberOf
		}
		qQueryMemberOf := swag.FormatBool(qrQueryMemberOf)
		if qQueryMemberOf != "" {
			if err := r.SetQueryParam("query_member_of", qQueryMemberOf); err != nil {
				return err
			}
		}

	}

	if o.ResolveNames != nil {

		// query param resolve_names
		var qrResolveNames bool
		if o.ResolveNames != nil {
			qrResolveNames = *o.ResolveNames
		}
		qResolveNames := swag.FormatBool(qrResolveNames)
		if qResolveNames != "" {
			if err := r.SetQueryParam("resolve_names", qResolveNames); err != nil {
				return err
			}
		}

	}

	if o.Resume != nil {

		// query param resume
		var qrResume string
		if o.Resume != nil {
			qrResume = *o.Resume
		}
		qResume := qrResume
		if qResume != "" {
			if err := r.SetQueryParam("resume", qResume); err != nil {
				return err
			}
		}

	}

	if o.Zone != nil {

		// query param zone
		var qrZone string
		if o.Zone != nil {
			qrZone = *o.Zone
		}
		qZone := qrZone
		if qZone != "" {
			if err := r.SetQueryParam("zone", qZone); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
