// Code generated by go-swagger; DO NOT EDIT.

package upgrade

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/tenortim/isi_sdk_go/models"
)

// NewCreateClusterRetryLastActionItemParams creates a new CreateClusterRetryLastActionItemParams object
// with the default values initialized.
func NewCreateClusterRetryLastActionItemParams() *CreateClusterRetryLastActionItemParams {
	var ()
	return &CreateClusterRetryLastActionItemParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateClusterRetryLastActionItemParamsWithTimeout creates a new CreateClusterRetryLastActionItemParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateClusterRetryLastActionItemParamsWithTimeout(timeout time.Duration) *CreateClusterRetryLastActionItemParams {
	var ()
	return &CreateClusterRetryLastActionItemParams{

		timeout: timeout,
	}
}

// NewCreateClusterRetryLastActionItemParamsWithContext creates a new CreateClusterRetryLastActionItemParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateClusterRetryLastActionItemParamsWithContext(ctx context.Context) *CreateClusterRetryLastActionItemParams {
	var ()
	return &CreateClusterRetryLastActionItemParams{

		Context: ctx,
	}
}

// NewCreateClusterRetryLastActionItemParamsWithHTTPClient creates a new CreateClusterRetryLastActionItemParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateClusterRetryLastActionItemParamsWithHTTPClient(client *http.Client) *CreateClusterRetryLastActionItemParams {
	var ()
	return &CreateClusterRetryLastActionItemParams{
		HTTPClient: client,
	}
}

/*CreateClusterRetryLastActionItemParams contains all the parameters to send to the API endpoint
for the create cluster retry last action item operation typically these are written to a http.Request
*/
type CreateClusterRetryLastActionItemParams struct {

	/*ClusterRetryLastActionItem*/
	ClusterRetryLastActionItem *models.ClusterRetryLastActionItem

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create cluster retry last action item params
func (o *CreateClusterRetryLastActionItemParams) WithTimeout(timeout time.Duration) *CreateClusterRetryLastActionItemParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create cluster retry last action item params
func (o *CreateClusterRetryLastActionItemParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create cluster retry last action item params
func (o *CreateClusterRetryLastActionItemParams) WithContext(ctx context.Context) *CreateClusterRetryLastActionItemParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create cluster retry last action item params
func (o *CreateClusterRetryLastActionItemParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create cluster retry last action item params
func (o *CreateClusterRetryLastActionItemParams) WithHTTPClient(client *http.Client) *CreateClusterRetryLastActionItemParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create cluster retry last action item params
func (o *CreateClusterRetryLastActionItemParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithClusterRetryLastActionItem adds the clusterRetryLastActionItem to the create cluster retry last action item params
func (o *CreateClusterRetryLastActionItemParams) WithClusterRetryLastActionItem(clusterRetryLastActionItem *models.ClusterRetryLastActionItem) *CreateClusterRetryLastActionItemParams {
	o.SetClusterRetryLastActionItem(clusterRetryLastActionItem)
	return o
}

// SetClusterRetryLastActionItem adds the clusterRetryLastActionItem to the create cluster retry last action item params
func (o *CreateClusterRetryLastActionItemParams) SetClusterRetryLastActionItem(clusterRetryLastActionItem *models.ClusterRetryLastActionItem) {
	o.ClusterRetryLastActionItem = clusterRetryLastActionItem
}

// WriteToRequest writes these params to a swagger request
func (o *CreateClusterRetryLastActionItemParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ClusterRetryLastActionItem != nil {
		if err := r.SetBodyParam(o.ClusterRetryLastActionItem); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
