// Code generated by go-swagger; DO NOT EDIT.

package upgrade

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/tenortim/isi_sdk_go/models"
)

// NewCreateClusterUpgradeItemParams creates a new CreateClusterUpgradeItemParams object
// with the default values initialized.
func NewCreateClusterUpgradeItemParams() *CreateClusterUpgradeItemParams {
	var ()
	return &CreateClusterUpgradeItemParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateClusterUpgradeItemParamsWithTimeout creates a new CreateClusterUpgradeItemParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateClusterUpgradeItemParamsWithTimeout(timeout time.Duration) *CreateClusterUpgradeItemParams {
	var ()
	return &CreateClusterUpgradeItemParams{

		timeout: timeout,
	}
}

// NewCreateClusterUpgradeItemParamsWithContext creates a new CreateClusterUpgradeItemParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateClusterUpgradeItemParamsWithContext(ctx context.Context) *CreateClusterUpgradeItemParams {
	var ()
	return &CreateClusterUpgradeItemParams{

		Context: ctx,
	}
}

// NewCreateClusterUpgradeItemParamsWithHTTPClient creates a new CreateClusterUpgradeItemParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateClusterUpgradeItemParamsWithHTTPClient(client *http.Client) *CreateClusterUpgradeItemParams {
	var ()
	return &CreateClusterUpgradeItemParams{
		HTTPClient: client,
	}
}

/*CreateClusterUpgradeItemParams contains all the parameters to send to the API endpoint
for the create cluster upgrade item operation typically these are written to a http.Request
*/
type CreateClusterUpgradeItemParams struct {

	/*ClusterUpgradeItem*/
	ClusterUpgradeItem *models.ClusterUpgradeItem

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create cluster upgrade item params
func (o *CreateClusterUpgradeItemParams) WithTimeout(timeout time.Duration) *CreateClusterUpgradeItemParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create cluster upgrade item params
func (o *CreateClusterUpgradeItemParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create cluster upgrade item params
func (o *CreateClusterUpgradeItemParams) WithContext(ctx context.Context) *CreateClusterUpgradeItemParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create cluster upgrade item params
func (o *CreateClusterUpgradeItemParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create cluster upgrade item params
func (o *CreateClusterUpgradeItemParams) WithHTTPClient(client *http.Client) *CreateClusterUpgradeItemParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create cluster upgrade item params
func (o *CreateClusterUpgradeItemParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithClusterUpgradeItem adds the clusterUpgradeItem to the create cluster upgrade item params
func (o *CreateClusterUpgradeItemParams) WithClusterUpgradeItem(clusterUpgradeItem *models.ClusterUpgradeItem) *CreateClusterUpgradeItemParams {
	o.SetClusterUpgradeItem(clusterUpgradeItem)
	return o
}

// SetClusterUpgradeItem adds the clusterUpgradeItem to the create cluster upgrade item params
func (o *CreateClusterUpgradeItemParams) SetClusterUpgradeItem(clusterUpgradeItem *models.ClusterUpgradeItem) {
	o.ClusterUpgradeItem = clusterUpgradeItem
}

// WriteToRequest writes these params to a swagger request
func (o *CreateClusterUpgradeItemParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ClusterUpgradeItem != nil {
		if err := r.SetBodyParam(o.ClusterUpgradeItem); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
