// Code generated by go-swagger; DO NOT EDIT.

package upgrade

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/tenortim/isi_sdk_go/models"
)

// NewUpdateClusterUpgradeParams creates a new UpdateClusterUpgradeParams object
// with the default values initialized.
func NewUpdateClusterUpgradeParams() *UpdateClusterUpgradeParams {
	var ()
	return &UpdateClusterUpgradeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateClusterUpgradeParamsWithTimeout creates a new UpdateClusterUpgradeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateClusterUpgradeParamsWithTimeout(timeout time.Duration) *UpdateClusterUpgradeParams {
	var ()
	return &UpdateClusterUpgradeParams{

		timeout: timeout,
	}
}

// NewUpdateClusterUpgradeParamsWithContext creates a new UpdateClusterUpgradeParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateClusterUpgradeParamsWithContext(ctx context.Context) *UpdateClusterUpgradeParams {
	var ()
	return &UpdateClusterUpgradeParams{

		Context: ctx,
	}
}

// NewUpdateClusterUpgradeParamsWithHTTPClient creates a new UpdateClusterUpgradeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateClusterUpgradeParamsWithHTTPClient(client *http.Client) *UpdateClusterUpgradeParams {
	var ()
	return &UpdateClusterUpgradeParams{
		HTTPClient: client,
	}
}

/*UpdateClusterUpgradeParams contains all the parameters to send to the API endpoint
for the update cluster upgrade operation typically these are written to a http.Request
*/
type UpdateClusterUpgradeParams struct {

	/*ClusterUpgrade*/
	ClusterUpgrade *models.ClusterUpgrade

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update cluster upgrade params
func (o *UpdateClusterUpgradeParams) WithTimeout(timeout time.Duration) *UpdateClusterUpgradeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update cluster upgrade params
func (o *UpdateClusterUpgradeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update cluster upgrade params
func (o *UpdateClusterUpgradeParams) WithContext(ctx context.Context) *UpdateClusterUpgradeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update cluster upgrade params
func (o *UpdateClusterUpgradeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update cluster upgrade params
func (o *UpdateClusterUpgradeParams) WithHTTPClient(client *http.Client) *UpdateClusterUpgradeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update cluster upgrade params
func (o *UpdateClusterUpgradeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithClusterUpgrade adds the clusterUpgrade to the update cluster upgrade params
func (o *UpdateClusterUpgradeParams) WithClusterUpgrade(clusterUpgrade *models.ClusterUpgrade) *UpdateClusterUpgradeParams {
	o.SetClusterUpgrade(clusterUpgrade)
	return o
}

// SetClusterUpgrade adds the clusterUpgrade to the update cluster upgrade params
func (o *UpdateClusterUpgradeParams) SetClusterUpgrade(clusterUpgrade *models.ClusterUpgrade) {
	o.ClusterUpgrade = clusterUpgrade
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateClusterUpgradeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ClusterUpgrade != nil {
		if err := r.SetBodyParam(o.ClusterUpgrade); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
