// Code generated by go-swagger; DO NOT EDIT.

package namespace

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/tenortim/isi_sdk_go/models"
)

// CopyDirectoryReader is a Reader for the CopyDirectory structure.
type CopyDirectoryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CopyDirectoryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCopyDirectoryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCopyDirectoryOK creates a CopyDirectoryOK with default headers values
func NewCopyDirectoryOK() *CopyDirectoryOK {
	return &CopyDirectoryOK{}
}

/*CopyDirectoryOK handles this case with default header values.

Copied directory.
*/
type CopyDirectoryOK struct {
	Payload *models.CopyErrors
}

func (o *CopyDirectoryOK) Error() string {
	return fmt.Sprintf("[PUT /namespace/{DirectoryCopyTarget}][%d] copyDirectoryOK  %+v", 200, o.Payload)
}

func (o *CopyDirectoryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CopyErrors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
