// Code generated by go-swagger; DO NOT EDIT.

package namespace

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/tenortim/isi_sdk_go/models"
)

// DeleteAccessPointReader is a Reader for the DeleteAccessPoint structure.
type DeleteAccessPointReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAccessPointReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteAccessPointOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteAccessPointOK creates a DeleteAccessPointOK with default headers values
func NewDeleteAccessPointOK() *DeleteAccessPointOK {
	return &DeleteAccessPointOK{}
}

/*DeleteAccessPointOK handles this case with default header values.

Deleted access point.
*/
type DeleteAccessPointOK struct {
	Payload models.Empty
}

func (o *DeleteAccessPointOK) Error() string {
	return fmt.Sprintf("[DELETE /namespace/{AccessPointName}][%d] deleteAccessPointOK  %+v", 200, o.Payload)
}

func (o *DeleteAccessPointOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
