// Code generated by go-swagger; DO NOT EDIT.

package cluster

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetTimezoneSettingsParams creates a new GetTimezoneSettingsParams object
// with the default values initialized.
func NewGetTimezoneSettingsParams() *GetTimezoneSettingsParams {

	return &GetTimezoneSettingsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetTimezoneSettingsParamsWithTimeout creates a new GetTimezoneSettingsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetTimezoneSettingsParamsWithTimeout(timeout time.Duration) *GetTimezoneSettingsParams {

	return &GetTimezoneSettingsParams{

		timeout: timeout,
	}
}

// NewGetTimezoneSettingsParamsWithContext creates a new GetTimezoneSettingsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetTimezoneSettingsParamsWithContext(ctx context.Context) *GetTimezoneSettingsParams {

	return &GetTimezoneSettingsParams{

		Context: ctx,
	}
}

// NewGetTimezoneSettingsParamsWithHTTPClient creates a new GetTimezoneSettingsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetTimezoneSettingsParamsWithHTTPClient(client *http.Client) *GetTimezoneSettingsParams {

	return &GetTimezoneSettingsParams{
		HTTPClient: client,
	}
}

/*GetTimezoneSettingsParams contains all the parameters to send to the API endpoint
for the get timezone settings operation typically these are written to a http.Request
*/
type GetTimezoneSettingsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get timezone settings params
func (o *GetTimezoneSettingsParams) WithTimeout(timeout time.Duration) *GetTimezoneSettingsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get timezone settings params
func (o *GetTimezoneSettingsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get timezone settings params
func (o *GetTimezoneSettingsParams) WithContext(ctx context.Context) *GetTimezoneSettingsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get timezone settings params
func (o *GetTimezoneSettingsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get timezone settings params
func (o *GetTimezoneSettingsParams) WithHTTPClient(client *http.Client) *GetTimezoneSettingsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get timezone settings params
func (o *GetTimezoneSettingsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetTimezoneSettingsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
