// Code generated by go-swagger; DO NOT EDIT.

package cluster

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/tenortim/isi_sdk_go/models"
)

// UpdateClusterNodeReader is a Reader for the UpdateClusterNode structure.
type UpdateClusterNodeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateClusterNodeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewUpdateClusterNodeNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewUpdateClusterNodeDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewUpdateClusterNodeNoContent creates a UpdateClusterNodeNoContent with default headers values
func NewUpdateClusterNodeNoContent() *UpdateClusterNodeNoContent {
	return &UpdateClusterNodeNoContent{}
}

/*UpdateClusterNodeNoContent handles this case with default header values.

Success.
*/
type UpdateClusterNodeNoContent struct {
}

func (o *UpdateClusterNodeNoContent) Error() string {
	return fmt.Sprintf("[PUT /platform/3/cluster/nodes/{ClusterNodeId}][%d] updateClusterNodeNoContent ", 204)
}

func (o *UpdateClusterNodeNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateClusterNodeDefault creates a UpdateClusterNodeDefault with default headers values
func NewUpdateClusterNodeDefault(code int) *UpdateClusterNodeDefault {
	return &UpdateClusterNodeDefault{
		_statusCode: code,
	}
}

/*UpdateClusterNodeDefault handles this case with default header values.

Unexpected error
*/
type UpdateClusterNodeDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the update cluster node default response
func (o *UpdateClusterNodeDefault) Code() int {
	return o._statusCode
}

func (o *UpdateClusterNodeDefault) Error() string {
	return fmt.Sprintf("[PUT /platform/3/cluster/nodes/{ClusterNodeId}][%d] updateClusterNode default  %+v", o._statusCode, o.Payload)
}

func (o *UpdateClusterNodeDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
