// Code generated by go-swagger; DO NOT EDIT.

package cluster

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/tenortim/isi_sdk_go/models"
)

// UpdateClusterOwnerReader is a Reader for the UpdateClusterOwner structure.
type UpdateClusterOwnerReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateClusterOwnerReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewUpdateClusterOwnerNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewUpdateClusterOwnerDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewUpdateClusterOwnerNoContent creates a UpdateClusterOwnerNoContent with default headers values
func NewUpdateClusterOwnerNoContent() *UpdateClusterOwnerNoContent {
	return &UpdateClusterOwnerNoContent{}
}

/*UpdateClusterOwnerNoContent handles this case with default header values.

Success.
*/
type UpdateClusterOwnerNoContent struct {
}

func (o *UpdateClusterOwnerNoContent) Error() string {
	return fmt.Sprintf("[PUT /platform/1/cluster/owner][%d] updateClusterOwnerNoContent ", 204)
}

func (o *UpdateClusterOwnerNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateClusterOwnerDefault creates a UpdateClusterOwnerDefault with default headers values
func NewUpdateClusterOwnerDefault(code int) *UpdateClusterOwnerDefault {
	return &UpdateClusterOwnerDefault{
		_statusCode: code,
	}
}

/*UpdateClusterOwnerDefault handles this case with default header values.

Unexpected error
*/
type UpdateClusterOwnerDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the update cluster owner default response
func (o *UpdateClusterOwnerDefault) Code() int {
	return o._statusCode
}

func (o *UpdateClusterOwnerDefault) Error() string {
	return fmt.Sprintf("[PUT /platform/1/cluster/owner][%d] updateClusterOwner default  %+v", o._statusCode, o.Payload)
}

func (o *UpdateClusterOwnerDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
