// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CloudAccountExtended cloud account extended
// swagger:model CloudAccountExtended
type CloudAccountExtended struct {
	CloudAccount

	// The machine generated name of the account bucket to store data
	Bucket string `json:"bucket,omitempty"`

	// A globally unique name for this account
	ID string `json:"id,omitempty"`

	// The machine generated name of the account bucket to store metadata
	MetadataBucket string `json:"metadata_bucket,omitempty"`

	// Name of the pool referencing this account.  Empty if none.
	Pool string `json:"pool,omitempty"`

	// Indicates whether this account is in a good state ("OK"), disabled ("disabled") or inaccessible via the network ("unreachable")
	// Enum: [OK disabled unreachable]
	State string `json:"state,omitempty"`

	// Gives further information to describe the state of this account
	StateDetails string `json:"state_details,omitempty"`

	// The type of cloud protocol required.  E.g., "isilon" for EMC Isilon, "ecs" for EMC ECS Appliance, "virtustream" for Virtustream Storage Cloud, "azure" for Microsoft Azure and "s3" for Amazon S3
	// Enum: [isilon ecs virtustream azure s3 ran ecs2]
	Type string `json:"type,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *CloudAccountExtended) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 CloudAccount
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.CloudAccount = aO0

	// AO1
	var dataAO1 struct {
		Bucket string `json:"bucket,omitempty"`

		ID string `json:"id,omitempty"`

		MetadataBucket string `json:"metadata_bucket,omitempty"`

		Pool string `json:"pool,omitempty"`

		State string `json:"state,omitempty"`

		StateDetails string `json:"state_details,omitempty"`

		Type string `json:"type,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO1); err != nil {
		return err
	}

	m.Bucket = dataAO1.Bucket

	m.ID = dataAO1.ID

	m.MetadataBucket = dataAO1.MetadataBucket

	m.Pool = dataAO1.Pool

	m.State = dataAO1.State

	m.StateDetails = dataAO1.StateDetails

	m.Type = dataAO1.Type

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m CloudAccountExtended) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(m.CloudAccount)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	var dataAO1 struct {
		Bucket string `json:"bucket,omitempty"`

		ID string `json:"id,omitempty"`

		MetadataBucket string `json:"metadata_bucket,omitempty"`

		Pool string `json:"pool,omitempty"`

		State string `json:"state,omitempty"`

		StateDetails string `json:"state_details,omitempty"`

		Type string `json:"type,omitempty"`
	}

	dataAO1.Bucket = m.Bucket

	dataAO1.ID = m.ID

	dataAO1.MetadataBucket = m.MetadataBucket

	dataAO1.Pool = m.Pool

	dataAO1.State = m.State

	dataAO1.StateDetails = m.StateDetails

	dataAO1.Type = m.Type

	jsonDataAO1, errAO1 := swag.WriteJSON(dataAO1)
	if errAO1 != nil {
		return nil, errAO1
	}
	_parts = append(_parts, jsonDataAO1)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this cloud account extended
func (m *CloudAccountExtended) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with CloudAccount
	if err := m.CloudAccount.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateState(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var cloudAccountExtendedTypeStatePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["OK","disabled","unreachable"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		cloudAccountExtendedTypeStatePropEnum = append(cloudAccountExtendedTypeStatePropEnum, v)
	}
}

// property enum
func (m *CloudAccountExtended) validateStateEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, cloudAccountExtendedTypeStatePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *CloudAccountExtended) validateState(formats strfmt.Registry) error {

	if swag.IsZero(m.State) { // not required
		return nil
	}

	// value enum
	if err := m.validateStateEnum("state", "body", m.State); err != nil {
		return err
	}

	return nil
}

var cloudAccountExtendedTypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["isilon","ecs","virtustream","azure","s3","ran","ecs2"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		cloudAccountExtendedTypeTypePropEnum = append(cloudAccountExtendedTypeTypePropEnum, v)
	}
}

// property enum
func (m *CloudAccountExtended) validateTypeEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, cloudAccountExtendedTypeTypePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *CloudAccountExtended) validateType(formats strfmt.Registry) error {

	if swag.IsZero(m.Type) { // not required
		return nil
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", m.Type); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CloudAccountExtended) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CloudAccountExtended) UnmarshalBinary(b []byte) error {
	var res CloudAccountExtended
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
