// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// ClusterTimezoneSettingsExtended cluster timezone settings extended
// swagger:model ClusterTimezoneSettingsExtended
type ClusterTimezoneSettingsExtended struct {

	// Timezone hierarchical name.
	Path string `json:"path,omitempty"`
}

// Validate validates this cluster timezone settings extended
func (m *ClusterTimezoneSettingsExtended) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ClusterTimezoneSettingsExtended) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ClusterTimezoneSettingsExtended) UnmarshalBinary(b []byte) error {
	var res ClusterTimezoneSettingsExtended
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
