// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ClusterTimeExtended cluster time extended
// swagger:model ClusterTimeExtended
type ClusterTimeExtended struct {

	// The current time on the cluster as a UNIX epoch (seconds since 1/1/1970), as reported by this node.
	// Required: true
	// Maximum: 4.294967295e+09
	// Minimum: 0
	Time *int64 `json:"time"`
}

// Validate validates this cluster time extended
func (m *ClusterTimeExtended) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTime(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ClusterTimeExtended) validateTime(formats strfmt.Registry) error {

	if err := validate.Required("time", "body", m.Time); err != nil {
		return err
	}

	if err := validate.MinimumInt("time", "body", int64(*m.Time), 0, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("time", "body", int64(*m.Time), 4.294967295e+09, false); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ClusterTimeExtended) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ClusterTimeExtended) UnmarshalBinary(b []byte) error {
	var res ClusterTimeExtended
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
