// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// EventEventgroupOccurrence Ignore flag for eventgroup.
// swagger:model EventEventgroupOccurrence
type EventEventgroupOccurrence struct {

	// True if eventgroup is to be ignored
	Ignore bool `json:"ignore,omitempty"`

	// True if eventgroup is to be resolved
	Resolved bool `json:"resolved,omitempty"`
}

// Validate validates this event eventgroup occurrence
func (m *EventEventgroupOccurrence) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *EventEventgroupOccurrence) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EventEventgroupOccurrence) UnmarshalBinary(b []byte) error {
	var res EventEventgroupOccurrence
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
