// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// EventAlertConditions event alert conditions
// swagger:model EventAlertConditions
type EventAlertConditions struct {

	// alert conditions
	AlertConditions []*EventAlertConditionsAlertCondition `json:"alert-conditions"`
}

// Validate validates this event alert conditions
func (m *EventAlertConditions) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAlertConditions(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *EventAlertConditions) validateAlertConditions(formats strfmt.Registry) error {

	if swag.IsZero(m.AlertConditions) { // not required
		return nil
	}

	for i := 0; i < len(m.AlertConditions); i++ {
		if swag.IsZero(m.AlertConditions[i]) { // not required
			continue
		}

		if m.AlertConditions[i] != nil {
			if err := m.AlertConditions[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("alert-conditions" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *EventAlertConditions) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EventAlertConditions) UnmarshalBinary(b []byte) error {
	var res EventAlertConditions
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
