// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// JobType job type
// swagger:model JobType
type JobType struct {

	// Whether the job type is enabled and able to run.
	Enabled bool `json:"enabled,omitempty"`

	// Default impact policy of this job type.
	Policy string `json:"policy,omitempty"`

	// Default priority of this job type; lower numbers preempt higher numbers.
	// Maximum: 10
	// Minimum: 1
	Priority int64 `json:"priority,omitempty"`

	// The schedule on which this job type is queued, if any.
	Schedule string `json:"schedule,omitempty"`
}

// Validate validates this job type
func (m *JobType) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePriority(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *JobType) validatePriority(formats strfmt.Registry) error {

	if swag.IsZero(m.Priority) { // not required
		return nil
	}

	if err := validate.MinimumInt("priority", "body", int64(m.Priority), 1, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("priority", "body", int64(m.Priority), 10, false); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *JobType) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *JobType) UnmarshalBinary(b []byte) error {
	var res JobType
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
