// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// JobJobDomainmarkParams job job domainmark params
// swagger:model JobJobDomainmarkParams
type JobJobDomainmarkParams struct {

	// Whether this is a delete operation.
	Delete bool `json:"delete,omitempty"`

	// Base IFS path to associate with the domain.
	// Required: true
	Root *string `json:"root"`

	// The type of domain.
	// Required: true
	// Enum: [SnapRevert SyncIQ Worm]
	Type *string `json:"type"`
}

// Validate validates this job job domainmark params
func (m *JobJobDomainmarkParams) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRoot(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *JobJobDomainmarkParams) validateRoot(formats strfmt.Registry) error {

	if err := validate.Required("root", "body", m.Root); err != nil {
		return err
	}

	return nil
}

var jobJobDomainmarkParamsTypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["SnapRevert","SyncIQ","Worm"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		jobJobDomainmarkParamsTypeTypePropEnum = append(jobJobDomainmarkParamsTypeTypePropEnum, v)
	}
}

const (

	// JobJobDomainmarkParamsTypeSnapRevert captures enum value "SnapRevert"
	JobJobDomainmarkParamsTypeSnapRevert string = "SnapRevert"

	// JobJobDomainmarkParamsTypeSyncIQ captures enum value "SyncIQ"
	JobJobDomainmarkParamsTypeSyncIQ string = "SyncIQ"

	// JobJobDomainmarkParamsTypeWorm captures enum value "Worm"
	JobJobDomainmarkParamsTypeWorm string = "Worm"
)

// prop value enum
func (m *JobJobDomainmarkParams) validateTypeEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, jobJobDomainmarkParamsTypeTypePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *JobJobDomainmarkParams) validateType(formats strfmt.Registry) error {

	if err := validate.Required("type", "body", m.Type); err != nil {
		return err
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", *m.Type); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *JobJobDomainmarkParams) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *JobJobDomainmarkParams) UnmarshalBinary(b []byte) error {
	var res JobJobDomainmarkParams
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
