// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// NamespaceObject namespace object
// swagger:model NamespaceObject
type NamespaceObject struct {

	// Specifies the date when the object was last accessed in HTTP date/time format.
	AccessTime string `json:"access_time,omitempty"`

	// Specifies the time when the object was last accessed in UNIX Epoch format.
	AtimeVal int64 `json:"atime_val,omitempty"`

	// Specifies the block size of the object.
	BlockSize int64 `json:"block_size,omitempty"`

	// Specifies the number of blocks that compose the object.
	Blocks int64 `json:"blocks,omitempty"`

	// Specifies the time when the object data was created in UNIX Epoch format.
	BtimeVal int64 `json:"btime_val,omitempty"`

	// Specifies the date when the object was last changed (including data and metadata changes) in HTTP date/time format.
	ChangeTime string `json:"change_time,omitempty"`

	// Specifies the name of the queried container.
	Container string `json:"container,omitempty"`

	// Specifies the container path on the file system.
	ContainerPath string `json:"container_path,omitempty"`

	// Specifies the date when the object data was created in HTTP date/time format.
	CreateTime string `json:"create_time,omitempty"`

	// Specifies the time when the object was last changed (including data and metadata changes) in UNIX Epoch format.
	CtimeVal int64 `json:"ctime_val,omitempty"`

	// Specifies the GID for the owner.
	Gid int64 `json:"gid,omitempty"`

	// Specifies the group name for the owner of the object.
	Group string `json:"group,omitempty"`

	// Specifies the object ID, which is also the INODE number.
	ID int64 `json:"id,omitempty"`

	// Specifies whether the file is hidden or not.
	IsHidden bool `json:"is_hidden,omitempty"`

	// Specifies the time when the object data was last modified in HTTP date/time format.
	LastModified string `json:"last_modified,omitempty"`

	// Specifies the UNIX mode octal number.
	Mode string `json:"mode,omitempty"`

	// Specifies the time when the object data was last modified in UNIX Epoch format.
	MtimeVal int64 `json:"mtime_val,omitempty"`

	// Specifies the name of the object.
	Name string `json:"name,omitempty"`

	// Specifies the number of hard links to the object.
	Nlink int64 `json:"nlink,omitempty"`

	// Specifies the user name for the owner of the object.
	Owner string `json:"owner,omitempty"`

	// Specifies the size of the object in bytes.
	Size int64 `json:"size,omitempty"`

	// Specifies whether the file is a stub or not.
	Stub bool `json:"stub,omitempty"`

	// Specifies the object type, which can be one of the following values: container, object, pipe, character_device, block_device, symbolic_link, socket, or whiteout_file.
	Type string `json:"type,omitempty"`

	// Specifies the UID for the owner.
	UID int64 `json:"uid,omitempty"`
}

// Validate validates this namespace object
func (m *NamespaceObject) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NamespaceObject) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NamespaceObject) UnmarshalBinary(b []byte) error {
	var res NamespaceObject
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
