// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// NdmpDiagnostics ndmp diagnostics
// swagger:model NdmpDiagnostics
type NdmpDiagnostics struct {

	// diagnostics
	Diagnostics *NdmpDiagnosticsDiagnostics `json:"diagnostics,omitempty"`
}

// Validate validates this ndmp diagnostics
func (m *NdmpDiagnostics) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDiagnostics(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *NdmpDiagnostics) validateDiagnostics(formats strfmt.Registry) error {

	if swag.IsZero(m.Diagnostics) { // not required
		return nil
	}

	if m.Diagnostics != nil {
		if err := m.Diagnostics.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("diagnostics")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *NdmpDiagnostics) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NdmpDiagnostics) UnmarshalBinary(b []byte) error {
	var res NdmpDiagnostics
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
