// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// SettingsGlobal settings global
// swagger:model SettingsGlobal
type SettingsGlobal struct {

	// Specifies the properties for global authentication settings.
	GlobalSettings *SettingsGlobalGlobalSettings `json:"global_settings,omitempty"`
}

// Validate validates this settings global
func (m *SettingsGlobal) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateGlobalSettings(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SettingsGlobal) validateGlobalSettings(formats strfmt.Registry) error {

	if swag.IsZero(m.GlobalSettings) { // not required
		return nil
	}

	if m.GlobalSettings != nil {
		if err := m.GlobalSettings.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("global_settings")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SettingsGlobal) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SettingsGlobal) UnmarshalBinary(b []byte) error {
	var res SettingsGlobal
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
