// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// SnapshotLocks snapshot locks
// swagger:model SnapshotLocks
type SnapshotLocks struct {

	// locks
	Locks []*SnapshotLockExtended `json:"locks"`
}

// Validate validates this snapshot locks
func (m *SnapshotLocks) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLocks(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SnapshotLocks) validateLocks(formats strfmt.Registry) error {

	if swag.IsZero(m.Locks) { // not required
		return nil
	}

	for i := 0; i < len(m.Locks); i++ {
		if swag.IsZero(m.Locks[i]) { // not required
			continue
		}

		if m.Locks[i] != nil {
			if err := m.Locks[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("locks" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *SnapshotLocks) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SnapshotLocks) UnmarshalBinary(b []byte) error {
	var res SnapshotLocks
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
