// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// WormCreateParams worm create params
// swagger:model WormCreateParams
type WormCreateParams struct {

	// Specifies whether to commit the file to a WORM state after the retention date is set.
	CommitToWorm *bool `json:"commit_to_worm,omitempty"`

	// Specifies the retention expiration date string in Coordinated Universal Time (UTC/GMT).
	WormRetentionDate string `json:"worm_retention_date,omitempty"`
}

// Validate validates this worm create params
func (m *WormCreateParams) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *WormCreateParams) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WormCreateParams) UnmarshalBinary(b []byte) error {
	var res WormCreateParams
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
